### ISSUE TITLE
Account Overview Page

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/myaccount#1]
Page: Overview 

Display on login/entering My Account

* [x] Messages: problems with account
  * [x] Patron Standing Alerts for `DELINQUENT`, `BARRED`, `BLOCKED` and `COLLECTION`
* [x] Fines (total owed in $)
* [x] Total items checked out
   * [x] Total items Overdue
* [x] Total items on hold
  * [x] Total item ready for pickup
* [x] Additional links

**Comment by banukutlu** [comment]
What are the possible Alert messages for patron standing?
and for which ones there should be an alert message on the summary page?

**Comment by ruthtillman** [comment]
@banukutlu that is a good question. Waiting to see if @mkutch has any other answers, but I have only seen Delinquent on my account.

The two real negative statuses are BARRED and BLOCKED. I believe BLOCKED corresponds to DELINQUENT. I believe BARRED means they need to opt into the garnishment -- is this correct, Maryam? So in that case, it we might need to put in a link for opting into garnishment.

**Comment by banukutlu** [comment]
@mkutch what are the other alerts (other than delinquent) that are displayed on the summary page currently?

**Comment by mkutch** [comment]
Confirmed with Chris that DELINQUENT, BARRED and BLOCKED are the onyl alerts. There are certain thresholds which the library has set that triggers which status a patron will be. We are testing something else  to see if another condition/alert shows up . Will let you know.

**Comment by mkutch** [comment]
When a user is sent to COLLECTION this is the alert.

![image](https://user-images.githubusercontent.com/43478453/70470879-063a6f00-1a9a-11ea-9d5f-ebbbbef82b42.png)

**Comment by ruthtillman** [comment]
Seems good.
