### ISSUE TITLE
Patron profiles

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/myaccount#10]
Ability to add information about patron like email, phone and address.

Not scoped for initial release but would be nice

**Comment by cdmo** [comment]
Need to fix/remove this broken link when the time comes. I understand that the current system cannot be modified.

![Screenshot 2020-03-05 09 05 15](https://user-images.githubusercontent.com/523381/75989021-81a49480-5ec0-11ea-9446-9497910e447b.png)

**Comment by cdmo** [comment]
@ruthtillman will be bringing issues that were discussed during my account checkin today to the Sirsi Steer team

**Comment by cdmo** [comment]
will tackle this later, as per check in meeting

**Comment by cdmo** [comment]
@mkutch "Foreign Address" is not a state.

![Screen Shot 2020-10-07 at 10 43 45 AM](https://user-images.githubusercontent.com/523381/95346635-1245b780-088a-11eb-92ff-91d2745f7710.png)

So questions for you:

* do we have users with "foreign addresses"?
* how do we handle these? the current form does not appear to handle "foreign addresses" - or does it? Maybe we could consider an option to toggle "inside or outside USA" instead of this?

**Comment by cdmo** [comment]
@ruthtillman 

Thinking about address updating link placement:

in the utility nav area like: [Screenshot_2020-10-12 My Account Pennsylvania State University Libraries](https://user-images.githubusercontent.com/523381/95802783-66a6c800-0ccc-11eb-8697-9e0123f88785.png)

in the main menu like: [Screenshot_2020-10-12 My Account Pennsylvania State University Libraries(1)](https://user-images.githubusercontent.com/523381/95802789-69a1b880-0ccc-11eb-9c3e-5b9dd6ff596b.png)

Thinking of other options, could make a "{Your name here} are signed in" with "Your name here" as a link to this patron address form?

Could use a FontAwesome icon like https://fontawesome.com/v4.7.0/icon/address-card-o or maybe just a generic person silhouette one?

Other UI ideas?

**Comment by ruthtillman** [comment]
🤔 the link might be a little subtle in that it could also imply to people that it was some kind of link to your summary page, etc. But I think maybe adding a link next to your name? as either:

- [address-card-o] with tooltip "Update address"
- or linked text: `(update address)`

so like:

Library account record for **Ruth Tillman** (update address) 

thoughts? 

(I'm technically logged in to work on something else but)

**Comment by cdmo** [comment]
Yeah a tooltip would be good especially if we don't use a lot of text for the link. Main menu item or secondary/utility item you tnihk?

**Comment by cdmo** [comment]
So I think it'll have to be, for space's sake, just "Update Address" - or something with a similarly small character count otherwise it'll look a little funky in the main menu I think

**Comment by cdmo** [comment]
@ruthtillman 

Should we keep the field "campus" as is? Or change it to "pickup location" and use the same translation dictionary as we use in the rest of myaccount?

![Screen Shot 2020-10-14 at 2 13 53 PM](https://user-images.githubusercontent.com/523381/96028671-9ae2cb80-0e27-11eb-8a3d-4266c421acb2.png)

**Comment by ruthtillman** [comment]
I think let's keep to Campus for now. Esp since Pickup Location dictionary is based on other labels because of the pandemic.

**Comment by ruthtillman** [comment]
Tested and works as expected! Only change would be changing zip label to "ZIP Code" to support people who may not recognize "ZIP" on its own.
