### ISSUE TITLE
New hold form

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/myaccount#106]
from #96

**Comment by cdmo** [comment]
@ruthtillman 

Do you have a preference in what we display to patrons in terms of items? Elibrary shows just the volume and I set My Account to show the whole call number. Now I'm not sure which we'd want. Here's a side by side:

![Screenshot 2020-02-11 09 53 40](https://user-images.githubusercontent.com/523381/74247774-9b353080-4cb4-11ea-8832-f958090ccd45.png)


Maybe we should just display the volume. The display call number for the current issue of the National Review is just "Periodical" which is confusing (not that a hold request for the current issue of the National Review would work anyway, but just saying)

**Comment by ruthtillman** [comment]
Good question! Let's go with the volume segment. It takes up less screen real estate and the call number portion should almost never matter.

**Comment by mkutch** [comment]
@ruthtillman can you take a look at this too? Their will be cases where there is no volume data.


![image](https://user-images.githubusercontent.com/43478453/74264775-3fc46c00-4ccf-11ea-9281-ac40eb66df5a.png)

**Comment by ruthtillman** [comment]
Oh jeez, that is a good point @mkutch ... it also seems like the micro thing might be more useful than just no 29

I guess that's an argument to keep it. It would be too much overkill to do something v. detailed around it.

**Comment by cdmo** [comment]
Re-opening, this still needs to be reviewed

**Comment by ruthtillman** [comment]
Looking good. Re: the date picker, I think auto-populating (like we do in e-Library) it is probably a better idea than forcing the user to do so. Maybe 3 months out? When using it on my computer, one time I accidentally selected tomorrow and had to go back and fix it. Auto-populating and letting the user change seems like a friendlier choice for now.

**Comment by cdmo** [comment]
@ruthtillman see #110. In e-library the default is 2 months from today so that's what we went with. I am deploying the code change (which hasn't been reviewed by @banukutlu just yet)  to heroku now so you can take a look.
