### ISSUE TITLE
Group things.

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/myaccount#112]
Stems from #106 

* Group all non-volumetrics (see `476022`, ~the most recent publication~ is grouped across locations and `15513` - actually this isn't the "most recent publication" - it's actually more likely to be "things we don't understand better" but we are still grouping them together because we lack better data)
* Group volumetrics of the same call together (see `7517385`)

This will mimic e-library

**Comment by cdmo** [comment]
After discussing with @mkutch and Jeff in Maryam's office, we went over some scenarios and believe that it may be best for user experience to show call numbers always and to not group non-volumetrics. Tagging this as question so we can bring it up at our next meeting.

**Comment by cdmo** [comment]
We talked about this during our check in meeting, indeed we will not be grouping non-volumetrics.

**Comment by cdmo** [comment]
After discussing with @mkutch and Jeff Edmunds, we've landed at "we should indeed continue to group non-volumetric holdables" - the reason being that there is a bit of a black box in terms of how a hold placement is processed once received and we want to play it safe and mirror the current process so as not to disrupt service/process.

**Comment by cdmo** [comment]
volumetrics that are of different call must be grouped in the new request form too.

non-volumetrics are grouped regardless of call number.

**Comment by cdmo** [comment]
@ruthtillman We group all non-volumetrics together regardless of call. So this can get a little weird. For example, see `15513`. In e-library we don't display call so it's just a parenthetical with locations (which is not good UX of course). In MyAccount we are display call number of course. So, I think we can just not display a call number when grouped? Or display all of them? Not sure.

![Screenshot 2020-03-03 15 43 00](https://user-images.githubusercontent.com/523381/75817720-acc6a100-5d65-11ea-887b-cf49123b1e25.png)

**Comment by cdmo** [comment]
Maybe it should just be like:

* [ ] Book

So just displaying the item type.

**Comment by cdmo** [comment]
For now I'm just picking the first Call and using it's call number. So in the above case that's 

![Screenshot 2020-03-04 15 59 14](https://user-images.githubusercontent.com/523381/75922501-1c559280-5e31-11ea-83e8-8b49544419ce.png)

**Comment by ruthtillman** [comment]
Check what's happening with Shenango in http://myaccount-qa.herokuapp.com/holds/new?catkey=7517385

**Comment by ruthtillman** [comment]
The display of the call number in the catalog vs. the display in the I Want It screen vs. the display in successful "I Want It" results seems to differ in whether "DVD disc" is added or not... is it grouping successfully because of the variance? Is it not?

**Comment by ruthtillman** [comment]
@mkutch what happens if every other disc 7 is made unavailable... then will our new holds placement place a hold on the Shenango disc 7?

**Comment by cdmo** [comment]
Just wanted to write out that what we learned with 7517385 is that there is an inconsistent "DVD" present in volumetric, however, the display call numbers are the same (the shenango copies must put `DVD` in the call number)

**Comment by ruthtillman** [comment]
Did some tests and this appears to be behaving well!
