### ISSUE TITLE
Synchronize data on pickup locations

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/myaccount#114]
Currently, pickup locations drop-down and display are coming from two different data sources. Synchronize to match the display to the drop-down, e.g. Pattee Commons desk vs. Pattee/Paterno Stacks.

**Comment by cdmo** [comment]
Just want to mention that the list of locations to choose is a custom list set by Chris in the current e-library system - so we do have parity with e-library as it is right now. Translations for pickup location codes in the hold tables are done with a custom map we load from My Account.

But, I guess my point is that he knows that it is custom and different. I wonder if we should check with him on this?

@mkutch is there a query like the itemType one to the web service we could use to get dynamic mappings of library names from code (like `UP-PAT` = "Pattee Commons Desk")?

**Comment by cdmo** [comment]
Will bring Chris H into this conversation, maybe the next My Account checkin, @ruthtillman will be coordinating that

**Comment by ruthtillman** [comment]
@mkutch can you share the location of the h-file -- privately is fine.

**Comment by ruthtillman** [comment]
Update: these change so rarely that we will keep the change manual.
