### ISSUE TITLE
Volumetrics - 1 item as hidden input

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/myaccount#115]
If only one item of a multi-volume set should be holdable, e.g. there's an ebook copy + a print copy, then pass the item info as a hidden input and don't display the volume selection screen.

**Comment by mkutch** [comment]
catkeys 
`15186836` 
`67483`

**Comment by cdmo** [comment]
For `72376`

There are a total of 10 potential holdable items. After filtering out those that have current locations that are not holdable there are 7. Of these 7, 6 have values for volumetric. So the result is this

![Screenshot 2020-02-13 10 02 32](https://user-images.githubusercontent.com/523381/74447928-1aa73900-4e48-11ea-9e57-fe148266b331.png)

Can you double check that one?

This is what it looks like in elibrary for reference

![Screenshot 2020-02-13 10 05 09](https://user-images.githubusercontent.com/523381/74448084-5d691100-4e48-11ea-8e54-847ef86f86d1.png)

**Comment by cdmo** [comment]
`15186836` is good. One ebook and one physical local holding.

**Comment by cdmo** [comment]
Okay, now for `15513` @mkutch 

5 potential holdables. 3 that have holdable current locations. There _is_ only one of those three that has a volumetric, however, the current logic dictates that for a set to be presented to the patron there need only be one volumetric and one or more other item regardless of volumetric status.

![Screenshot 2020-02-13 10 21 27](https://user-images.githubusercontent.com/523381/74449463-9ace9e00-4e4a-11ea-878a-d727bf8bfb49.png)

Now... something odd with this one though. The Harrisburg copy (`QE157.S26x`) does not show up in elibrary, but it does show up in our my account implementation. 🤔

![Screenshot 2020-02-13 10 24 52](https://user-images.githubusercontent.com/523381/74449783-14668c00-4e4b-11ea-95d6-4e788e5125c0.png)

**Comment by cdmo** [comment]
@banukutlu and @ruthtillman for testing purposes of this issue, please refer to `15186836` and `67483` (@banukutlu is reviewing now, nothing for you just yet @ruthtillman)

**Comment by mkutch** [comment]
catkey `72376` - looks good AND filtering out online is an improvement ... I see of the 7, 7 has volumetrics. Is that also what you see on your end?

catkey `15513` - see in e-library the list of libraries next to the first checkbox and you see Harrisburg. so they are grouping all the non-volumetrics together

**Comment by ruthtillman** [comment]
The one-item issue has been solved, but it needs splitting out to address other questions raised?

**Comment by cdmo** [comment]
@mkutch as you said, `72376` does look good (online option filtered). All volumetrics are showing.

`15513` will be handled in #112
