### ISSUE TITLE
Confirm WebServices version/protocols

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/myaccount#117]
We are building against test, which uses a different version of WebServices than prod. Before releasing, we will need to be sure that our app can run against prod. Review WebServices documentation?

**Comment by banukutlu** [comment]
@mktuch Are there any updates on prod version update? We have been developing against the new version 6.0 with the expectation that this will be the version the prod will be updated to eventually?

**Comment by mkutch** [comment]
No news on when prod will be updated to version 6.0.  In the meantime, @tdouty will install web services on the development with the same version as production (2017 version).

**Comment by cdmo** [comment]
Yeah, i am not super interested personally in testing our current code on 2017. I view that as a Plan B for sure. Testing our code on the 2017 version seems especially like wasted effort given that the plan is to upgrade production to 6.0 imminently.

I think I would like to get a better sense of how we can upgrade production to 6.0. If the answer to this question, line of thinking is, "well, it just isn't feasible, it's going to be too hard" or something like that, then fine, but it'd be better to not have to do the extra testing work on the 2017 version (plus making any necessary modifications to the code based on that change, which again, would likely be short-lived given that 6.0 will be on production _soon_)

**Comment by banukutlu** [comment]
> Yeah, i am not super interested personally in testing our current code on 2017. I view that as a Plan B for sure. Testing our code on the 2017 version seems especially like wasted effort given that the plan is to upgrade production to 6.0 imminently.

I totally agree with this, testing our code on 2017 version right now, would mean an extra cycle of testing for the already closed issues, and another cycle when prod updated. And this is even without taking potentially having to change things into account...

**Comment by tdouty** [comment]
I think the answer is to get SirsiDynix to make this their highest priority. I just sent another email to them. Charlie is on it, but I did not add Banu. I may send it out again with Banu added.


Todd Douty <todd.douty@psu.edu>

Systems Administrator

The Pennsylvania State University Libraries

(814) 865-4850

________________________________

**Comment by cdmo** [comment]
I wanted to write down our hallway-meeting decision so that @banukutlu knows what's going on and we don't forget what we decided:

* The plan for now is to wait and see if the upgrade of web services to 6.0 on our production instance occurs. 
* Current issue blocking the upgrade has been ongoing since November and may be resolved tomorrow or a year from now.
* If web services is not upgraded to 6.0 and we're getting close to launching we'll just have to either *a)* test/develop against 2017 or *b)* wait some more

**Comment by banukutlu** [comment]
per @mkutch 
> SirsiDynix upgraded Production Web Services to 6.0.0
