### ISSUE TITLE
Workaround for records in use response

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/myaccount#120]
Symphony responses with `"The records are currently in use.  Please try again later."` error msg when canceling or placing multiple holds, and seems like after these actions since the record is busy, item info can not be retrieved as well.

We might have to take a try again approach as a workaround.

**Comment by cdmo** [comment]
I believe @mkutch put in a ticket with Sirsi on this. Any response?

**Comment by mkutch** [comment]
Sirsi hasn't been able to replicate the issue in-house yet. They asked for some info which I responded.

**Comment by cdmo** [comment]
Ok. I think then we'll wait until that thread resolves before jumping in to fix this on our end then.

**Comment by cdmo** [comment]
@mkutch and I worked to create reproducible steps for the vendor, the vendor verified the issue and acknowledged it's happening for them too. Their response is that we must just send repeat queries (as we have suspected). So this issue can be worked on now.

**Comment by ruthtillman** [comment]
I don't know exactly how to test this, but reading through the process looks good.
