### ISSUE TITLE
Check items against holdmap policy

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/myaccount#122]
itemType, item library and permission

AND user profile  

EDIT: combining with #123

**Comment by mkutch** [comment]
and user profile

**Comment by cdmo** [comment]
I split user profile into a separate issue (#123), but perhaps this should just be one. Want to note that Chris was in favor.

**Comment by cdmo** [comment]
in our check in meeting today @ruthtillman approved this method with a caveat to see how page performance was affected on the new hold form for volumetrics with lots of items (like national review)

**Comment by cdmo** [comment]
@mkutch wanted to put this issue on hold until she conducts more research

**Comment by cdmo** [comment]
@mkutch is this still on hold, did you want to do more research still?

**Comment by mkutch** [comment]
@cdmo Since we want to mirror the current process we won't be doing this, so we can close it.

**Comment by cdmo** [comment]
Ok. We can always return to it later if we feel like it's worth doing. Thanks.
