### ISSUE TITLE
Validation for holds#new catkey presence

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/myaccount#131]
If not, redirect to catalog homepage

**Comment by cdmo** [comment]
@banukutlu is it maybe ok to just have the default 500 error appear? Thinking that this isn't really needed anymore. What would be the scenario where someone did pass along a catkey, you know? It's not something they choose in a form...

**Comment by banukutlu** [comment]
> @banukutlu is it maybe ok to just have the default 500 error appear? Thinking that this isn't really needed anymore. What would be the scenario where someone did pass along a catkey, you know? It's not something they choose in a form...

Yes, it makes sense 👍
