### ISSUE TITLE
Document how web services is upgraded regularly 

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/myaccount#134]
We need to create a document to cement our understanding of when and how the web services will be updated for ongoing maintenance of the application.

**Comment by cdmo** [comment]
@mkutch can you tell me what the communication channel is for updates? How is it decided that the web services software will be updated and how can we get notified?

**Comment by mkutch** [comment]
Sirsi steer committee decides the updates of that and @ruthtillman is on that committee.

**Comment by cdmo** [comment]
ok. Great. I see the team page on the staff site. Looks like they meet once a month and we'd be notified by them when upgrades happen. Thanks.
