### ISSUE TITLE
Don't link if shadowed *OR if it's equip7day5*

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/myaccount#162]
See holobar's account, it's trying to link to a shadowed item

Thanks @mkutch for finding this

@mkutch can you let us know what field indicates shadowed?

**Comment by mkutch** [comment]
@cdmo When you do a bib level web service call the field is called `shadowed` and the values are true and false.

**Comment by cdmo** [comment]
Perfect, thanks.

**Comment by ruthtillman** [comment]
Checking Holobar's account, the Course Reserve isn't showing up but equip7day5 test up (catkey 29014105) is still showing up linked... is this a different to-do?

**Comment by banukutlu** [comment]
> Checking Holobar's account, the Course Reserve isn't showing up but equip7day5 test up (catkey 29014105) is still showing up linked... is this a different to-do?

That one has an item type that was only defined in test afaik, right @mkutch. We do not link several item types and this should be one of those normally.

**Comment by mkutch** [comment]
@banukutlu Yes, that item type is not in production policy.

**Comment by cdmo** [comment]
that will be fixed with #130

**Comment by cdmo** [comment]
#130 will provide dynamic itemType translations, and I can also add the filter for equip7day5 there too. Sound good?

**Comment by banukutlu** [comment]
> #130 will provide dynamic itemType translations, and I can also add the filter for equip7day5 there too. Sound good?

I think there is no need to add this type, afair that one is only added for testing purposes. @mkutch?

**Comment by cdmo** [comment]
Thought it was in test because it was going to be added to prod eventually?

**Comment by mkutch** [comment]
@banukutlu I emailed Chris asking if equipp7day5 was going to move into prod. His response

> I guess it was on my list to move over before the world ended

**Comment by cdmo** [comment]
So i'll add it to our exclusion list of linked items. (just coordinating with @banukutlu so we don't both do it)
