### ISSUE TITLE
Web service error logging and in-page error notifications to users

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/myaccount#179]
Create contents of the polling.js error function

- [x] Client side error notifications
- [x] ~Client side error logging~ see #207 
- [x] Server side error logging

from #166

**Comment by cdmo** [comment]
This came up at our checkin today, we and @ruthtillman all seemed to agree that using a Bootstrap Toast is probably a good idea to try as long as it can be canceled and is accessible

**Comment by cdmo** [comment]
I rigged up an example of how this will work. I think this is working for the most part, I do like it. It's less obtrusive than a modal window or an alert which is nice. Here's a demo, @ruthtillman what do you think? (apologies for poor image quality):

![toast](https://user-images.githubusercontent.com/523381/80033364-9366e900-84ba-11ea-930f-503972f53360.gif)

**Comment by ruthtillman** [comment]
Yes, I like the obvious redness when there's a problem and then the Redness of error.

If they're successful, will it still load the green box at the top or anything like that?

**Comment by ruthtillman** [comment]
I think if it's successful, then anything that needs to be closed like a toast is probably overkill, so loading in the older way would be better?

**Comment by cdmo** [comment]
toasts can be set to auto close after a duration. I was thinking that 10 seconds would be a reasonable amount of time for any toast to be closed (success or fail). For someone with a lot of items the toasts could pile up on a big requests, but not sure what else can be done about that. Toasts can also be positioned anywhere on the screen fwiw.

The older way could work okay, but, if a user is scrolled down at the bottom of the page adding a message at the top might be missed.

It's kinda tricky.

**Comment by cdmo** [comment]
Recap what we discussed at today's check in meeting:

- [ ] We'll only use toasts for errors
- [ ] Success will be shown as green checks  ✅  next to the update item after the spinner is gone and the new value is present.
- [ ] We'll need to make sure to translate errors as needed (as in error codes from Sirsi translated to human-understandable messages)
- [ ] Monitoring will be critical

**Comment by banukutlu** [comment]
just attaching a screenshot, it looks nice overall

<img width="1051" alt="Screen Shot 2020-07-02 at 7 23 33 PM" src="https://user-images.githubusercontent.com/6477867/86416983-aad00880-bc99-11ea-8c9d-7a033ace092a.png">

**Comment by banukutlu** [comment]
@ruthtillman Charlie and I wanted to get your feedback for how values look when a renewal or in general any action gets an error as response. See the above screenshot, currently we have `Error` as the value for those columns where we are expecting to change with a success. We talked about an idea of keeping the values and adding a warning icon next it like a triangle sign etc. to indicate that it did not change. What do you think?

**Comment by banukutlu** [comment]
@ruthtillman another question we had is for custom error messages #69, do we want these translation for all actions for renewals only?

**Comment by cdmo** [comment]
Hold creation can generate some vague error messages too though:

* `{"messageList":[{"code":"hatErrorResponse.17286","message":"Hold not allowed"}]}`
* `{"messageList":[{"code":"hatErrorResponse.722","message":"User already has a hold on this material"}]}`
* `{"messageList"=>[{"code"=>"recordNotFound", "message"=>"Could not find a(n) /catalog/bib record with the key 29233955."}]}`

Still not sure about a hold update error. Chris has maintained that it's pretty much impossible though I know I encountered it many times on test cat data earlier this year.

**Comment by ruthtillman** [comment]
ok, so catching up post-vacation!:

1. "We talked about an idea of keeping the values and adding a warning icon next it like a triangle sign etc. to indicate that it did not change. What do you think?" this sounds good. I prefer it to the text Error. 

2. Errors for both hold placement and renewals sounds good. I think for holds placement on that page itself -- it would be better to just load the page with the error embedded if it's denied vs. the popup. Because you're expecting the page to reload anyway with info. I think for the message--maybe preface with "Unable to place hold. Reason:" so `"Unable to place hold. Reason: User already has a hold on this material."`

3. Re: hold update errors... it sounds like we don't know exactly what those would be, so do we have any kind of generic way we could capture an error if exists? so just pass on the message if there is one and not land the user on a completely blank page?

**Comment by cdmo** [comment]
The error handling is setup such that it'll pass along the message from sirsi automatically unless we make a translation for the code associated with it because the text error message is so nonsensical. If it's a malformed response we just give a generic response. This response is what we wanted to hear, I think we're good. @banukutlu I'll modify the error notification feature to do the warning icon with original value thing.

**Comment by cdmo** [comment]
The only thing needing review on this is the error notifications on the frontend (the toasts for renewals and holds). Holds errors are seemingly impossible to recreate, but, if they ever happen again for whatever weird edge case I was in with holds a month or so ago, they'll be ready.

**Comment by ruthtillman** [comment]
Toasts look good.
