### ISSUE TITLE
Revise text about renewals and an overall review of labels in the application

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/myaccount#2]
- [ ] Work with Chris H. to revise text currently at the top of Checkouts/Renewals + add links to Illiad.
- [x] revise the "please wait, loading" text

**Comment by cdmo** [comment]
I'm interested in changing this to a general "overall review" of labels throughout.

**Comment by ruthtillman** [comment]
@cdmo that would be fine, yes.

**Comment by banukutlu** [comment]
Since this is now a more generic issue, could any message we show to users be revised as part of it? For example error messages for 404s and 500s #137

**Comment by cdmo** [comment]
This came up during the checkin this week: to revise the "please wait, loading" text

**Comment by ruthtillman** [comment]
Talked with KH and we started with: `Your items are loading. If you have a lot of items checked out, it will take some time for the page to load.` except that it will need to be broader to fit the holds page too....

**Comment by ruthtillman** [comment]
Ok, revised text which can be used on any kind of page: `Items are loading. Longer lists of items will take a few moments to load.`

**Comment by ruthtillman** [comment]
Looks good!
