### ISSUE TITLE
Resolve login issues

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/myaccount#20]
The desired outcome:

- [x] when a user goes to any page of the app that user is sent to authentication (webaccess)
- [x] app should detect for session renewal need (stale?) and automatically renew session token
~[x] encrypt~

**Comment by cdmo** [comment]
Re: encryption. This really doesn't make any sense as the auth info is passed as `GET` query params from the auth service. We would have to rewrite the auth service in order to hide these values.

**Comment by cdmo** [comment]
Stale appears to be working correctly in my testing

**Comment by ruthtillman** [comment]
Seems good.
