### ISSUE TITLE
Default hold pickup location to their campus if possible?

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/myaccount#206]
In the holds placement screen, can what we know about users so that if they're logged in, I'll show UP and someone else will show Beaver, etc? Do we have this info?

**Comment by mkutch** [comment]
For the call `/user/patron/key/{patron_key}` there's the `{library}` endpoint.

**Comment by cdmo** [comment]
@mkutch is this something we can depend on to be right? 

Also, where is this data set?

Here? 
![Screen Shot 2020-09-21 at 3 05 51 PM](https://user-images.githubusercontent.com/523381/93809982-f9979980-fc1b-11ea-92b2-89167072b493.png)

**Comment by mkutch** [comment]
@tdouty Please see Q above?

**Comment by ruthtillman** [comment]
💯
