### ISSUE TITLE
Pickup location should be configurable

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/myaccount#222]
This came out of this week's checkin meeting, we will make the list of pickup locations configurable due to the fact that they are very subject to change and the list is one of the few manually managed things in our application (we don't trust the data from the webservice on this information)

**Comment by cdmo** [comment]
@banukutlu can you try this out on QA?

**Comment by banukutlu** [comment]
> For the review @banukutlu can you try this out on QA? See #234

when I made a change to `settings.local.yml` it did not override (unless I missed sth) but `settings/production.local.yml` worked. maybe we should mention which file to use for the override?

**Comment by cdmo** [comment]
`settings.local.yml` _should_ override. But! `settings.local.yml` will be written (and over-written) by deploy scripts because that's where we're storing connection info and stuff. So, yeah we shouldn't use that anyway. I agree about updating the README to specify which file to add.

**Comment by banukutlu** [comment]
> `settings.local.yml` _should_ override. But! `settings.local.yml` will be written (and over-written) by deploy scripts because that's where we're storing connection info and stuff. So, yeah we shouldn't use that anyway. I agree about updating the README to specify which file to add.

I guess it was being overridden by `settings/production.local.yml`, will give it a try.

**Comment by cdmo** [comment]
Oh I see you had both at once. Yes, the order of precedence can be found here: https://github.com/rubyconfig/config#accessing-the-settings-object
