### ISSUE TITLE
Redirect to the original request url after auth

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/myaccount#236]
after webaccess, it does not redirect to the original request url, only redirects to summaries

**Comment by cdmo** [comment]
this is in qa

**Comment by ruthtillman** [comment]
QAd! Tested several different kinds of materials, including ones which couldn't be put on hold and everything behaved as expected.

**Comment by ruthtillman** [comment]
Did some more testing this afternoon. It works as expected for first login. However, if one has to re-login, it doesn't pass on the original request. Steps to replicate this issue:

1. On VPN, open un-logged-in browser and place hold, e.g. on https://blackcat01qa.libraries.psu.edu/catalog/25085728. This should work after WebAccess auth.
2. Disconnect VPN. Do something in WebAccess Auth which prompts reauth.
3. Reconnect VPN, in same browser attempt to place a hold on another item, e.g. https://blackcat01qa.libraries.psu.edu/catalog/9357690  
4. You will get WebAccess prompt to reauthenticate and this time it will load homepage.

Maybe this has to do with a slightly different method of reauth vs. auth? Hoping the same solution applies.

**Comment by banukutlu** [comment]
> 1. 25085728

I could not recreate this

**Comment by banukutlu** [comment]
> Did some more testing this afternoon. It works as expected for first login. However, if one has to re-login, it doesn't pass on the original request. Steps to replicate this issue (maybe...some time passed as well, so basically when back on VPN, it did the password re-entry prompt without requiring Duo or anything):
> 
> 1. On VPN, open un-logged-in browser and place hold, e.g. on https://blackcat01qa.libraries.psu.edu/catalog/25085728. This should work after WebAccess auth.
> 2. Disconnect VPN. Do something in WebAccess Auth which prompts reauth.
> 3. Reconnect VPN, in same browser attempt to place a hold on another item, e.g. https://blackcat01qa.libraries.psu.edu/catalog/9357690
> 4. You will get WebAccess prompt to reauthenticate and this time it will load homepage.
> 
> Maybe this has to do with a slightly different method of reauth vs. auth? Hoping the same solution applies.

I was not able to recreate this, it redirected to the correct page 🤔

**Comment by ruthtillman** [comment]
🤔 I will try to see if I can make it happen again this morning...

**Comment by cdmo** [comment]
I experienced a problem in the redirect this morning. When I had to do the webaccess "reauth" thing (not the full DUO authentication) it redirected to the summaries page instead of the new hold request form.

**Comment by ruthtillman** [comment]
☝️ this is what I was trying to describe, yeah. It's very hard to replicate because you have to let things go stale enough to force the reauth but not enough to force a new login.

**Comment by ruthtillman** [comment]
Updating to add that I have also had reauth work as desired. This inconsistency doesn't seem to happen with first-time auth, though. It's always working as expected. Unfortunately I don't know enough to speculate.

**Comment by cdmo** [comment]
I think one thing that will consistently trigger this is if your own IP changes (like what the VPN changes forced to happen as you described above)

**Comment by cdmo** [comment]
marking this closed, it is deployed to prod. if it occurs again we'll just open a new issue.
