### ISSUE TITLE
holds/new form throws an error when record has no holdables items

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/myaccount#237]
try `/holds/new?catkey=19200019`

<img width="1376" alt="Screen Shot 2020-08-25 at 4 21 32 PM" src="https://user-images.githubusercontent.com/6477867/91349040-b67c0f00-e7b2-11ea-8836-7866689d3fcc.png">

**Comment by banukutlu** [comment]
some notes from debugging this record:

currentLocations on this catkey are CHECKEDOUT, STACKS-BD, STACKS-HB3
STACKS-BD, STACKS-HB3 are not returning back from holdable_locations even though this catkey has IWantIt and availability returns `holdable`

**Comment by banukutlu** [comment]
Update: these locations were updated as holdable but cache needed to be cleared and server needed to be restarted on the sirsi side, after Maryam doing that, now those two locations shows up holdable. 

Also, added a fix for it to not error out in this case.

**Comment by cdmo** [comment]
I'm going to reopen this because I don't think it passed. Please correct me if I'm wrong.

**Comment by ruthtillman** [comment]
I QAd this one. I got the item itself to work successfully but when attempting other items which shouldn't be put on hold at all (just as an edge case), it didn't do anything. Should redirect to my acct home I believe.

**Comment by cdmo** [comment]
Ok cool. Just wasn't sure. Thanks.

**Comment by banukutlu** [comment]
reopened to add a message `Sorry! You cannot place a hold on this item. Contact your library if you need assistance` for records that are not holdable eg. catkey: `31200756`

**Comment by ruthtillman** [comment]
Tested with both online item and item which doesn't exist. Successful!
