### ISSUE TITLE
 Renew session functionality

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/myaccount#24]
potential approach: Ping symphony to see if the user token expired or not

**Comment by cdmo** [comment]
@banukutlu please tell me we just forgot to close this before right? RIGHT? 😆

**Comment by banukutlu** [comment]
> @banukutlu we just forgot to close this before right?

I think there was still some things we wanted to clear out but I honestly think it is fine, guess we both do not wanna change/refactor right now :) So yeah let's have this close :)
