### ISSUE TITLE
Accessibility Test Fixes Required

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/myaccount#247]
- [x] remove "--" in pickup locations select
- [x] Run deque axe matchers and fix all the things

**Comment by cdmo** [comment]
In the screen reader testing we have a glaring error of nothing being announced to the screen after renew or hold update. I am fixing that and it’s good. But… there is no definitive announcement like “successfully renewed” and Banu and I were thinking some subtle notification to sighted users might be helpful too. So, we came up with the idea of using a badge under the item to indicate things went well and this will also get announced to screenreaders. There may be a better more elegant solution out there, but I think we do need something..

<img width="979" alt="Screen Shot 2020-09-10 at 2 04 14 PM" src="https://user-images.githubusercontent.com/523381/92778938-9ed68600-f36f-11ea-8fd3-6c71c966a350.png">

(more on “badges” from twitter bootstrap: https://getbootstrap.com/docs/4.5/components/badge/) 

Ruth likes this idea too 👍

**Comment by ruthtillman** [comment]
Badges look good.
