### ISSUE TITLE
Add language re: Illiad/Medianet note appearing in checkouts or renewals

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/myaccount#265]
For checkouts/renewals page, display following message: "Materials borrowed through Illiad or Medianet do not appear on this list and must be renewed separately."

For holds page, display following: "Materials requested through Illiad or Medianet do not appear on this list and must be managed separately."

**Comment by ruthtillman** [comment]
Text is good -- can we link both "Illiad" and "Medianet" in a way that takes the user through auth to those sites? ... related, I don't know as much about Medianet and if it's still in place and how it works. If y'all don't either, lets check with Binky.

**Comment by ruthtillman** [comment]
@banukutlu After looking at the Medianet link, checked its name w/Binky. She says replace "Medianet" with "MTSS".

**Comment by ruthtillman** [comment]
It looks good except it's only appearing on Holds page vs. Checkouts/Renewals

**Comment by banukutlu** [comment]
> It looks good except it's only appearing on Holds page vs. Checkouts/Renewals

fix added

**Comment by ruthtillman** [comment]
QA completed, looks good.
