### ISSUE TITLE
Adding default pickup location means it's always updated in hold updates

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/myaccount#272]
We added a default pickup location selection (based on the user's data) to our hold placement form in order to ease the process.

This default also appears on the updates form in Holds.

When updating date requested by, the selected location will also update. This will result in messages saying that the location has updated, even if the user did not intend it to. Since users could change the selection and users are most likely to be getting all their holds in one place, it's not a blocker to release. But it might be a bit confusing.

Idea: would it be possible to return the location dropdown in Holds to a default of no selected location and only update the location if the user changes it?

Outcome of that would be that users get a default location when placing a hold but updates always require a selection and without that selection, it will only update the date (or give an error that nothing's been selected if a date is not selected either).

**Comment by cdmo** [comment]
> would it be possible to return the location dropdown in Holds to a default of no selected location and only update the location if the user changes it?

No problem 👍

**Comment by ruthtillman** [comment]
Tested updating location and date -- separately and simultaneously. All behaved as expected. 👍
