### ISSUE TITLE
Support users whose default location does not allow pickups during closure period

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/myaccount#274]
Because some libraries aren't doing pickup, it's possible a user's default location will not be allowing pickups.

If their default location is not matched in the list _when placing holds_, then make it blank to force selection.

**Comment by banukutlu** [comment]
@mkutch could we find a test account with a default library that is not doing pickup right now?

**Comment by ruthtillman** [comment]
Successfully tested with my default library, UP, removed from QA list! Looks good to go.
