### ISSUE TITLE
Renewals: Display summary of items renewed

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/myaccount#275]
When performing renewals, how can we display a summary at the end? 

What's been requested, what's the status, present nice little tally.

This is not a release blocker.

EDIT by @cdmo 10/27

After talking through at check-in, we're going to be displaying a gray bar with a message like "your blah is processing..." at the top (which has been scrolled-up to). After all requests are processed we will update that gray bar area with a tally of successful completions and unsuccessful requests"

**Comment by cdmo** [comment]
@ruthtillman Will there be a summary notification for holds batch operations too?

**Comment by ruthtillman** [comment]
@cdmo once we get the other sorted out, yes I think that would be a good enhancement.

**Comment by cdmo** [comment]
I updated the description of the issue, please edit away if it's off

**Comment by ruthtillman** [comment]
@banukutlu I think we are ok not doing that for now.
