### ISSUE TITLE
Update holds success message

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/myaccount#276]
Ruth contact Chris

**Comment by ruthtillman** [comment]
Also update font/color!

**Comment by ruthtillman** [comment]
Chris approves success message: "For placed hold(s), you will receive a library notice once items are available for pick up. Items generally arrive within 2-3 weekdays." cc @mkutch

**Comment by banukutlu** [comment]
> Chris approves success message: "For placed hold(s), you will receive a library notice once items are available for pick up. Items generally arrive within 2-3 weekdays." cc @mkutch

Is this to replace ```For placed hold(s), you will receive a library notice once items are available for pick up. On-shelf items generally arrive within 2-3 weekdays. Items checked out to other borrowers will be recalled. Recalled items take a minimum of 10 days to arrive at your pickup location.```?

**Comment by ruthtillman** [comment]
yes.

**Comment by banukutlu** [comment]
@ruthtillman can we separate pickup locations to match pandemic to another issue?

**Comment by ruthtillman** [comment]
👍
