### ISSUE TITLE
Ensure admin settings are correct

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/myaccount#278]
@mkutch ensure that admin settings on test and prod are the same to not break something in My Account.

Test/proof by pointing blackcat01qa to myaccount proper and be sure that holds place/fail etc (be sure to cancel too)

**Comment by mkutch** [comment]
I set  fillByDate to Editable in prod

**Comment by cdmo** [comment]
this can be closed now right?

**Comment by ruthtillman** [comment]
Yep
