### ISSUE TITLE
Update pickup libraries list & names to match pandemic

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/myaccount#281]
The libraries which can be pickup locations are in a state of flux because of the pandemic. We need to make sure our list matches prod. Also labels may temporarily include additional directions such as "pick up at the circle" so we'll need to update those too.

**Comment by cdmo** [comment]
I think I'm reading this wrong. "We need to make sure our list matches prod." - like "make sure catalog qa matches catalog prod?" Just want to make sure. Thanks

**Comment by ruthtillman** [comment]
@cdmo Symphony list has been updated.

**Comment by cdmo** [comment]
Can we ask whoever (Chris?) is having these changes happen start to email us too?

**Comment by ruthtillman** [comment]
I think so ... @mkutch is there a list where these are announced?

**Comment by mkutch** [comment]
Chris was emailing me , @banukutlu ,@cdmo  during the pandemic re campus pickup libraries

**Comment by cdmo** [comment]
👍 k he can continue to do that, cool. If he neglects one of us we'll send on

**Comment by cdmo** [comment]
worth mentioning once more: wish we had a unified set of labels for pickup locations. Right now we have two sets. What we use in the dropdown and what we display in the table aren't always the same.

**Comment by cdmo** [comment]
oh and qa and prod myaccount have the latest now (for the dropdown)
