### ISSUE TITLE
holds/result check for referer

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/myaccount#288]

**Comment by cdmo** [comment]
Think we should close 0.3x and mark the last deploy as 1.0, right?

**Comment by cdmo** [comment]
I'm sorry, but what is the problem that this issue is discussing? I think the title of the issue is the solution, but what was the problem? I apologize because I think this is something that you and Maryam spoke about but I didn't catch it.

**Comment by banukutlu** [comment]
I found about this while checking the issue Maryam brought up, it is again sth that we do not expect as a normal user behavior but if you directly go to /holds/result the page just keeps spinning, this is to check if it is a redirect from from holds/new

**Comment by cdmo** [comment]
So... we are fixing the problem of a weird experience for someone who types in `myaccount.libraries.psu.edu/holds/result` - is that right?

**Comment by banukutlu** [comment]
Yes, a new hold is not placed unwantedly or anything like that, just the page displays this msg `Attempting to place holds, please wait...`, it is just misleading.

**Comment by cdmo** [comment]
Ok yup, I did get it. Before I just didn't wait long enough. Sorry!

**Comment by ruthtillman** [comment]
Looks good!
