### ISSUE TITLE
Renewing items with session and active login that is expired

### ISSUE THREAD

**Issue by mkutch** [psu-libraries/myaccount#295]
I had a myaccount open from the previous day. I clicked on Renew items and it's just spinning.  I was able to recreate it in Chrome when I login in to my account and then cleared browsing data.  Same thing happens with any Hold activities too. Perhaps there should be some kind of redirect back to the catalog after certain amount of time, or check if the patron session has timed out and it redirects them back to catalog?

**Comment by cdmo** [comment]
That is supposed to be happening. Thanks for reporting.

**Comment by cdmo** [comment]
@mkutch you made this issue at 11:18 am this morning, can you tell me roughly when you attempted to renew and it just spun?

**Comment by cdmo** [comment]
@mkutch can you test this out on QA? Maybe leave your browser open over night there and see what happens tomorrow morning? Also, though it's not the exact same scenario, delete the website's cookie in-session to test too?

**Comment by cdmo** [comment]
this is in prod now, will close as we discussed in check-in
