### ISSUE TITLE
Dummy Accounts

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/myaccount#3]
* [x] Evaluate Stanford's list of dummy accounts and scenarios, update and address any necessary differences.
* [ ] Make them happen in Test.

**Comment by ruthtillman** [comment]
Documented on wiki page: https://github.com/psu-libraries/psulib_blacklight/wiki/Test-User-Types-for-My-Account with assistance from C.H.

**Comment by cdmo** [comment]
Should we close this one?
