### ISSUE TITLE
Research impacts of home library updates

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/myaccount#300]
We have temporarily frozen the home library update function. However, while undergraduates and maybe graduate students shouldn't be able to edit this, faculty, staff, and commonwealth patrons do not update automatically and should be able to change their own data. Can we confirm if there are any unknown dependencies on where the system uses this?

**Comment by mkutch** [comment]
Chris H. is looking into this.

**Comment by banukutlu** [comment]
@mkutch are there any updates on this?
