### ISSUE TITLE
Editing a blank address

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/myaccount#304]
state should be defaulting to a "Pick your state" option kind of thing

**Comment by cdmo** [comment]
@mkutch this is fixed in production, can you take a look and let me know if it is resolved?

**Comment by mkutch** [comment]
looks good 👍 

![image](https://user-images.githubusercontent.com/43478453/97475643-e1562100-1923-11eb-9638-7ae03d20cc17.png)

**Comment by cdmo** [comment]
great! thanks  Maryam!
