### ISSUE TITLE
Announcement bar functionality like is in the catalog

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/myaccount#331]
like

![Screen Shot 2020-12-03 at 3 58 19 PM](https://user-images.githubusercontent.com/523381/101087588-687c6180-3580-11eb-8599-ed42dd557698.png)

**Comment by cdmo** [comment]
this is in prod now, but @banukutlu  you want to review it?

**Comment by banukutlu** [comment]
> this is in prod now, but @banukutlu you want to review it?

yup, will do, thanks!

**Comment by banukutlu** [comment]
closing this, reviewed on qa and it worked 👍
