### ISSUE TITLE
401 Unauthorized occuring when token expires

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/myaccount#334]
[This type of error](https://app.datadoghq.com/apm/trace/4437928283688971723?spanID=822253331872102089&env=production&sort=time&colorBy=service&graphType=flamegraph&shouldShowLegend=true) the application probably going through its typical session renewal mechanism, which is expected behavior and probably can be caught instead of thrown.

I think this is an "inevitable exception" and that we should "branch around it" but I don't think that's possible. Think we have to use it as part of control flow (reading [How to Rescue Exceptions in Ruby](https://stackify.com/rescue-exceptions-ruby/))

**Comment by cdmo** [comment]
@mkutch could you tell me how long a token is good for?

**Comment by mkutch** [comment]
In the knowledge base it says

QUESTION:
When a user logs in to web services with the loginUser or patron/login call they get a session token.  How long is that session token valid?

ANSWER:
The session token will stay valid for twelve hours as long as it is still being used to make requests.  It will time out after two hours when it is idle.

are you experiencing something different? I've also put in a ticket asking if that is something that be changed or not.

**Comment by cdmo** [comment]
Thanks! Great info. No need to change in my opinion, but nice to know. I'm just attempting to clean up some logs.

I haven't experienced anything different no.
