### ISSUE TITLE
Unknown method in batch delete operation

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/myaccount#336]
[`nil` doesn't know that method](https://app.datadoghq.com/apm/trace/3783217875663766069?spanID=3451875372237139261&env=production&sort=time&colorBy=service&graphType=flamegraph&shouldShowLegend=true) kind of error going on at https://github.com/psu-libraries/myaccount/blob/master/app/controllers/holds_controller.rb#L86

Probably when delete button is submitted without any checkboxes clicked

**Comment by banukutlu** [comment]
this seems to be solved with #347
