### ISSUE TITLE
Add error code 238 to sirsi response translations

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/myaccount#339]
This error code returned when couple users tried to renew Hathi ETAS items which were auto-renewed. We got servicenow tickets (INC1592348, INC1592358) because the users got the generic error message. Adding a custom message would be more clear for user.

```{"messageList"=>[{"code"=>"hatErrorResponse.238", "message"=>"User cannot check out this item"}], "describeUri"=>"/exception/advicePrompt", "promptRequired"=>false, "dataMap"=>{"recommendedAction"=>"/circulation/itemCircInfo/advise"}}```

**Comment by cdmo** [comment]
Thanks for adding this. I wonder if this 238 error also shows up for non-ETAS things.

**Comment by banukutlu** [comment]
> Thanks for adding this. I wonder if this 238 error also shows up for non-ETAS things.

yeah, I assume it would show up but do not know yet in which cases. @mkutch is this sth we can find out?

**Comment by cdmo** [comment]
Just not sure what the translation would or should be, what are you going to make it?

**Comment by banukutlu** [comment]
> Just not sure what the translation would or should be, what are you going to make it?

Not sure yet, after finding out in which cases this code is returned we might be able to come up with sth. and will get @ruthtillman input on the msg text as well.

**Comment by cdmo** [comment]
Ok, cool. Saw you self assigned so was wondering if you were jumping on it or not. Think it's safe to get to in January 👍

**Comment by banukutlu** [comment]
> Ok, cool. Saw you self assigned so was wondering if you were jumping on it or not. Think it's safe to get to in January 👍

yeah, not starting on it yet, will wait ;)

**Comment by banukutlu** [comment]
@ruthtillman any thoughts on what should the custom error msg for this error be? Currently, it does not seem much helpful? @mkutch in which cases do we get `hatErrorResponse.238` other than renewal attempt on HathiETAS items?

**Comment by ruthtillman** [comment]
Talked to Chris, we settled on "This item cannot be automatically renewed. Please contact ul-lending@lists.psu.edu for assistance in renewing the item."

**Comment by banukutlu** [comment]
tested on QA ✔️ 
<img width="366" alt="Screen Shot 2021-02-22 at 3 51 07 PM" src="https://user-images.githubusercontent.com/6477867/108768722-02233180-7526-11eb-9a1a-98852aa706d7.png">

**Comment by ruthtillman** [comment]
Looks great!

**Comment by cdmo** [comment]
deployed
