### ISSUE TITLE
holds pickup date update issue on Safari

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/myaccount#346]
<img width="1314" alt="Screen Shot 2021-01-22 at 3 01 05 PM" src="https://user-images.githubusercontent.com/6477867/105548993-5ee4bf80-5cce-11eb-96eb-0f3013961e6b.png">

<img width="1299" alt="Screen Shot 2021-01-22 at 3 07 28 PM" src="https://user-images.githubusercontent.com/6477867/105548911-4379b480-5cce-11eb-9fd3-55fb704b4f1e.png">

**Comment by ruthtillman** [comment]
Tested fixes in Safari and Edge, both behaved as expected. Used Safari 13, so I saw the date placeholder as well.
