### ISSUE TITLE
"I want it" not working from Summon

### ISSUE THREAD

**Issue by mkutch** [psu-libraries/myaccount#352]
Searched for a book in Summon then clicked "I want it" link in Summon. Took me to the Myaccount page with this message "Sorry! You cannot place a hold on this item. Contact your library if you need assistance." I can place a hold on the book from the Catalog or CAT.

**Comment by cdmo** [comment]
I think I see what's happening

I just went to https://psu.summon.serialssolutions.com/advanced#!/search/document?ho=t&l=en&q=(TitleCombined:(walk%20in%20the%20woods))&id=FETCHMERGED-psu_catalog_a179440442 and clicked the "I Want It" link in the right sidebar and experienced this issue. Looking at the url provided by the I Want It link, there seems to be a typo:

`https://myaccount.libraries.psu.edu/holds/new?catkey=a17944044`

It should be

`https://myaccount.libraries.psu.edu/holds/new?catkey=17944044`

So there's an extra little a after the equal sign. @ruthtillman is this something you fix? Or is this a thing you fix @mkutch? Not sure who manages this in Summon...

**Comment by ruthtillman** [comment]
Thanks for the diagnosis, @cdmo -- the problem here is that Summon thinks the catkeys begin with letters, e.g. "a" etc. So we need to find a way to have Summon strip those off or strip off the letter "a" on arriving catkey values. I will investigate Summon's side of things and talk to Maryam.

**Comment by ruthtillman** [comment]
Opened case with Summon: 00924829

**Comment by banukutlu** [comment]
@ruthtillman Just checking to see if there are any updated from Summon on this?

Also we are gonna sniff the leading `a` and remove it for placing holds.

**Comment by ruthtillman** [comment]
No action from Summon yet. I updated the ticket once. Thank you!
