### ISSUE TITLE
Add an error page for when symphony client returns no user

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/myaccount#375]
https://github.com/psu-libraries/myaccount/pull/362#discussion_r631959466

Some of the work done with #477 is relevant to this issue.

**Comment by ajkiessl** [comment]
@ruthtillman Do you think there should be any kind of instructions for the user when they are not found in Symphony?  Idk if this is common or if there's a procedure to get them a record in Symphony.  Perhaps we should direct them to Symphony?

**Comment by ruthtillman** [comment]
I think we should make it a fairly simple message, something like:

"No account found for [access ID]. Contact your library for any further assistance."
