### ISSUE TITLE
My Account "Bad Request" issue

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/myaccount#379]
Reported by a librarian. They tried in both Firefox and Chrome. I them advised to also be sure they're updated via BigFix while we look into it (and noted ServiceNow would be the fastest way to be sure it comes in, since I might be on vacation). Is this possibly related to the newest deploy?

>This week, when I've attempted to request an item from another campus, sometimes I get the following message on an otherwise blank screen:

    Bad Request
    Your browser sent a request that this server could not understand.
    Size of a request header field exceeds server limit.

>Sometimes I get this message when I first click on the I Want It button from the record and sometimes I get it when I click the Place Hold button on the next screen. Reloading the page has resolved the issue each time,  I think. (Sometimes I have to reload twice.) I've been requesting dozens of titles this week for a project and I think I've gotten this message approximately 50% of the time.

>This morning, while requesting some more titles, I'm now also occasionally seeing an additional issue. After clicking the Place Hold button, I get a spinning wheel to suggest it's loading with this message:  Attempting to place holds, please wait... (still framed with the My Account header and footer). This seems to go on forever. I would say I've gotten this message maybe 10% of the time this morning. Reloading the page does not resolve the issue in this case. When I backtrack in the browser and try again, it sometimes gives me the Bad Request message (which is resolved with reloading) or sometimes tells me that I already have a hold on the material (meaning the earlier request was successful even though it didn't want to load) or sometimes works fine.

**Comment by ruthtillman** [comment]
Update: follow-up email says that both Firefox and Chrome were already newest versions available in BigFix, so it's not an old browser issue!

**Comment by whereismyjetpack** [comment]
@ruthtillman I've adjusted the `LimitRequestFieldSize` value in the myaccount virtual host to mitigate this issue. I believe it to be resolved _for now_
