### ISSUE TITLE
`acknowledgeRenewalFeeCircPrompt` can be caught and treated like a regular “can’t renew, contact library” error.

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/myaccount#386]
`acknowledgeRenewalFeeCircPrompt` errors can be just caught and treated like a regular “can’t renew, contact library” error.
  - `Error 500: [{"code"=>"acknowledgeRenewalFeeCircPrompt", "message"=>"Renewal fee of 100.00 USD acknowledgment required."}` 
     - `/symwsbc/circulation/circRecord/renew`
  - [`Error 500: [{"code"=>"acknowledgeRenewalFeeCircPrompt", "message"=>"Renewal fee of 22.00 USD acknowledgment required."}`](https://app.datadoghq.com/apm/trace/620730435647640378?spanID=3743199735654951147&env=production&sort=time&colorBy=service&spanViewType=errors&graphType=flamegraph&shouldShowLegend=true)

**Comment by Smullz622** [comment]
@ruthtillman What was the question on this one?
