### ISSUE TITLE
More Sirsi codes to exclude from Datadog

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/myaccount#388]
[`Error 401: [{"code"=>"unableToLogin", "message"=>"Unable to log in."}]`](https://app.datadoghq.com/apm/trace/3037577098696853612?spanID=3866014215659514871&env=production&sort=time&colorBy=service&spanViewType=errors&graphType=flamegraph&shouldShowLegend=true)

[`Error 401: [{"code"=>"unableToLogin", "message"=>"Unable to log in."}]`](https://app.datadoghq.com/apm/trace/2664671281841403103?colorBy=service&env=production&graphType=flamegraph&shouldShowLegend=true&sort=desc&spanID=453422085368573178&spanViewType=metadata&timeHint=1631593955124.249)

[`Error 500: [{"code"=>"hatErrorResponse.18094", "message"=>"The user record is locked for text update"}]`](https://app.datadoghq.com/apm/trace/4339112958313207546?colorBy=service&env=production&graphType=flamegraph&shouldShowLegend=true&sort=time&spanID=1076288733901962942&spanViewType=metadata)

[`Error 500: [{"code"=>"hatErrorResponse.225", "message"=>"The bibliographic record is locked for text update"}]`](https://app.datadoghq.com/apm/trace/2321536965398728955?colorBy=service&env=production&graphType=flamegraph&shouldShowLegend=true&sort=desc&spanID=4354546476764940788&spanViewType=metadata&timeHint=1631102636844.469)

**Comment by ruthtillman** [comment]
Discussed briefly and are closing for now.
