### ISSUE TITLE
Bills

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/myaccount#4]
Show fines/bills

Show how to pay them.

Get screenshot from Chris, etc.

**Comment by cdmo** [comment]
@ruthtillman or @mkutch (not sure who to ask), Is it possible to get a patron dummy account with more than one fine? I have access to a dummy account with a single fine at the moment. Thanks.

**Comment by ruthtillman** [comment]
@mkutch I think this is something you or Chris could do?

**Comment by mkutch** [comment]
@cdmo I put one in box for you. Let me know if you need more.

**Comment by cdmo** [comment]
Thanks!

**Comment by cdmo** [comment]
Do we want format (aka "item type") to be a separate column? Or nested under title (as it is now in My Account)?

**Comment by ruthtillman** [comment]
I think either is fine if it’s aesthetically pleasing?

**Comment by cdmo** [comment]
Kinda like it nested in the title column, but, yeah, 6 to one half dozen the other.

**Comment by ruthtillman** [comment]
Display looks good but we need something on how to pay them: Show how to pay them.

**Comment by cdmo** [comment]
I don't think elibrary shows how to pay them, but, yeah, we definitely should detail that. Kind of an important detail! :)

My understanding is that it's done through the bursar's office. Is that right? Maybe we could get Chris to draft a blurb?

**Comment by cdmo** [comment]
![Screenshot 2020-01-31 10 03 23](https://user-images.githubusercontent.com/523381/73549631-f17eb580-4410-11ea-89fa-72cc7e0e0d7c.png)

**Comment by cdmo** [comment]
Flagging this as ready to be reviewed again (it is on QA) to check on the bills/fines that lead to error messages before? @ruthtillman

**Comment by ruthtillman** [comment]
Checked and looks good.

**Comment by cdmo** [comment]
Going to go ahead and close
