### ISSUE TITLE
Catkey 2972255 is failing

### ISSUE THREAD

**Issue by whereismyjetpack** [psu-libraries/myaccount#404]
When trying to place a hold for catkey the following line is throwing an error

https://github.com/psu-libraries/myaccount/blob/main/app/services/place_hold_form/builder.rb#L102

`call.record['naturalized_volumetric'] = naturalize(call.volumetric.to_s)` is producing the following 

```
    "naturalized_volumetric"=>["v", 2.0]}>,
```

then when calling `.sort_by! it's failing because naturalized_volumetric is an array with 

```
ArgumentError: comparison of Array with Array failed
```

it works with calling sort_by on the first object, or if you call .to_s on it but i'm not sure what the desired outcome is, I feel like to sort by naturalized_volumetric it would need to be an integer, yes?

**Comment by nicktiberi** [comment]
@mkutch (+ @ruthtillman) - Banu and I just looked at this, and it seems that for some of the holdings, we are not getting the year back in volumetric field in the response from Symphony.

```
[1] pry(#<PlaceHoldForm::Builder>)> @volumetric_calls[0].record['naturalized_volumetric']
=> [2005.0, "v", 1.0]
[2] pry(#<PlaceHoldForm::Builder>)> @volumetric_calls[1].record['naturalized_volumetric']
=> [2005.0, "v", 2.0]
[3] pry(#<PlaceHoldForm::Builder>)> @volumetric_calls[2].record['naturalized_volumetric']
=> [2005.0, "v", 3.0]
[4] pry(#<PlaceHoldForm::Builder>)> @volumetric_calls[3].record['naturalized_volumetric']
=> [2005.0, "v", 4.0]
[5] pry(#<PlaceHoldForm::Builder>)> @volumetric_calls[4].record['naturalized_volumetric']
=> ["v", 1.0] # expecting the year here
[6] pry(#<PlaceHoldForm::Builder>)> @volumetric_calls[5].record['naturalized_volumetric']
=> ["v", 4.0] # expecting the year here
[7] pry(#<PlaceHoldForm::Builder>)> @volumetric_calls[6].record['naturalized_volumetric']
=> ["v", 2.0] # expecting the year here
```

Attached example response file: 
[2972255.txt](https://github.com/psu-libraries/myaccount/files/7001325/2972255.txt)

Is this expected? Or should we be getting the year back for all records? Thanks!

The issue is that the `sort_by` is failing because it's trying to compare strings ("v") with numbers (2005.0) and that crashes the app.

**Comment by mkutch** [comment]
@nicktiberi It seems there are other records with this issue... see  catkeys `442922, 468031` and try to do an I want it and you get blank screen.

**Comment by ruthtillman** [comment]
Per checking the record, they should all have a "2005" of some kind in them (so probably 2005.0?)

**Comment by nicktiberi** [comment]
@ruthtillman @mkutch - do we think this is a data/cataloging issue (missing year in the source data)? Or is this maybe a bug on the Symphony side?

There are a few things we could do on the My Account side to stop the crashing, but I'm wondering if this should be handled by updating the data and/or changing something in Symphony.

**Comment by ruthtillman** [comment]
Since it's coming out wrong compared to what should be in there, @mkutch  can you see if there's anything unusual in the symphony side that is leading to it not exporting correctly? When I switch back to my work comp I can see if there's a coding issue in the item field or something...

**Comment by mkutch** [comment]
Looking at Workflows that's how they appear. Some of the callnumbers have the date and volume in the |z field and some don't (just has volume).  Maybe using the `sortCallNumber` endpoint could help? 
Here is that catkey's callnumber, volumetric and  normalized call number that is used for sorting by call number. 

```
Q181.K248 2005 v.1|v.1|Q  000181 .K248  2005  V.000001|
Q181.K248 2005 v.1|2005 v.1|Q  000181 .K248  002005 V.000001|
Q181.U438 2005 v.2|v.2|Q  000181 .U438  2005  V.000002|
Q181.K248 2005 v.2|2005 v.2|Q  000181 .K248  002005 V.000002|
Q181.K248 2005 v.4|2005 v.4|Q  000181 .K248  002005 V.000004|
Q181.K248 2005 v.3|2005 v.3|Q  000181 .K248  002005 V.000003|
Q181.K248 2005 v.4|v.4|Q  000181 .K248  2005  V.000004|

```

**Comment by ruthtillman** [comment]
@mkutch I went to look at the cataloging documentation and it appears the placement of the |z before the 2005 in records like this is standard practice, so this must be an oversight from when the items were created. I am going to edit this one record and then we can see how it impacts holds placement. If that solves the issue, then I'll edit the other two and maybe start passing them on as issues arise.

**Comment by whereismyjetpack** [comment]
I think this still begs the question, since the constraint isn't on the symphony side, should we handle these silently on our end? should we default that field to `0000` to avoid crashing? should we ignore the record? etc.

**Comment by ruthtillman** [comment]
In an ideal case, we'd get some kind of notification that lets us fix it / the person would get an error message of some kind to tell them to ask ul-lending for help.

**Comment by whereismyjetpack** [comment]
so, we could catch this error and say something like 'we had an issue placing a hold for this record, please ask a librarian for help' or something like this? is this required for placing the hold? should we halt the hold process if we don't have to?

**Comment by ruthtillman** [comment]
yes/no --- in a lot of cases they might be able to place the hold, however there might be some volumes that don't show up and these could be what they need.

**Comment by nicktiberi** [comment]
The crash is happening when myaccount tries to sort the data that comes back from Symphony. 

We could just catch the error and show the list in the original order, and everything should work fine (no issues placing holds, etc). We could even log these errors when they occur and then fix any underlying data issues. This would allow us to both avoid the app crashing and let us know when we need to fix up the data.

**Comment by ruthtillman** [comment]
@nicktiberi if that's feasible, that sounds good to me!

**Comment by mkutch** [comment]
others `50495, 55390`
