### ISSUE TITLE
Add Altoona locker location

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/myaccount#429]
Altoona has purchased some lockers for holds pickup and would like these added ASAP to the hold placement/pickup locations. I'll make the edit tonight. They're repurposing the UP-GATEWAY library because it costs $$ and time to add another location.

UP-GATEWAY: Penn State Altoona-Downtown

(it won't be anyone's default, obviosuly)

**Comment by ruthtillman** [comment]
Note: We added this but they will be renaming the library to LOCKER-AA, currently in the works with finance dept to pay Sirsi to make the change. I'll add a branch with this new library name but it shouldn't be merged yet

**Comment by mkutch** [comment]
Sirsi renamed UP-GATEWAY to AA-DOWNTWN on Prod on 9/22.  The renaming on Stage is on 9/29. 
Note :  Must restart web service after the rename so web services calls see that pickup library correctly.
