### ISSUE TITLE
Altoona pickup location to just Penn State Altoona

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/myaccount#442]
Change value for https://github.com/psu-libraries/myaccount/blob/main/config/settings.yml#L40 to `Penn State Altoona`.

**Comment by banukutlu** [comment]
@ruthtillman https://github.com/psu-libraries/myaccount/blob/1ec1a36187b1b70b2e637a8d2dc75c9dcf9bd8e8/config/settings.yml#L65 this should match right?

**Comment by ruthtillman** [comment]
That's a really good question -- I think it should actually be `Penn State Altoona - Library Circulation Desk` to parallel the locker one since there's two for Penn State Altoona. Thanks for catching it

**Comment by banukutlu** [comment]
@ruthtillman This change is merged so would be in QA but cannot be reviewed right now since symphony stage is not up due to Oracle patching.
