### ISSUE TITLE
My Account unvailable Friday November 5th, 6-7am

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/myaccount#443]
We'll be having an emergency patch on prod -- can we have the alert:

`My Account will be down for critical maintenance on Friday, November 5th, 6-7am.`

**Comment by banukutlu** [comment]
are we putting this one up now?

**Comment by ruthtillman** [comment]
Thurs morning would be ok if tonight isn't good

**Comment by banukutlu** [comment]
can do it now 👍🏻

**Comment by banukutlu** [comment]
done 👍🏻
