### ISSUE TITLE
Add patron standing COLLECTION alert to summary page

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/myaccount#45]
When a user is sent to collection this is the alert. The standing{key} is COLLECTION

![image](https://user-images.githubusercontent.com/43478453/70470879-063a6f00-1a9a-11ea-9d5f-ebbbbef82b42.png)

_Originally posted by @mkutch in https://github.com/psu-libraries/myaccount/issues/1#issuecomment-563427871_

**Comment by ruthtillman** [comment]
Looks good.
