### ISSUE TITLE
Volumetric not working for catkey 322209 

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/myaccount#470]
Got a report that it seems like volumetric processing isn't currently working right for this record: https://myaccount.libraries.psu.edu/holds/new?catkey=322209 

I checked and volumetrics are working on other records just fine. I looked at the data structure, though, and it seems to be correct. It's possible that the call # disambiguation isn't catching the difference between: `M127.S67 op.35 S36 bk.1 Q` and `M127.S67 op.35 S36 bk.2 Q` because of the Q?

**Comment by nicktiberi** [comment]
Looks like this may be an issue with the data in this record/on the Symphony side.

Looking at the data coming back from Symphony, `volumetric` is `nil` for both calls, so it's not being processed as volumetric:

```
"callList"=>
      [{"resource"=>"/catalog/call",
        "key"=>"322209:1",
        "fields"=>
         {"bib"=>{"resource"=>"/catalog/bib", "key"=>"322209"},
          "callNumber"=>"M127.S67 op.35 S36 bk.1 Q",
          "volumetric"=>nil,
          "dispCallNumber"=>"M127.S67 op.35 S36 bk.1 Q",
          "classification"=>{"resource"=>"/policy/classification", "key"=>"LC"},
          "library"=>{"resource"=>"/policy/library", "key"=>"UP-PAT"},
          "shadowed"=>false,
          "itemList"=>
           [{"resource"=>"/catalog/item",
             "key"=>"322209:1:1",
             "fields"=>
              {"bib"=>{"resource"=>"/catalog/bib", "key"=>"322209"},
               "call"=>{"resource"=>"/catalog/call", "key"=>"322209:1"},
               "barcode"=>"000013968854",
               "circulate"=>true,
               "copyNumber"=>1,
               "currentLocation"=>{"resource"=>"/policy/location", "key"=>"PATTEE-1A"},
               "homeLocation"=>{"resource"=>"/policy/location", "key"=>"PATTEE-1A"},
               "itemType"=>{"resource"=>"/policy/itemType", "key"=>"SCORE"},
               "library"=>{"resource"=>"/policy/library", "key"=>"UP-PAT"},
               "mediaDesk"=>nil,
               "shadowed"=>false}}]}},
       {"resource"=>"/catalog/call",
        "key"=>"322209:2",
        "fields"=>
         {"bib"=>{"resource"=>"/catalog/bib", "key"=>"322209"},
          "callNumber"=>"M127.S67 op.35 S36 bk.2 Q",
          "volumetric"=>nil,
          "dispCallNumber"=>"M127.S67 op.35 S36 bk.2 Q",
          "classification"=>{"resource"=>"/policy/classification", "key"=>"LC"},
          "library"=>{"resource"=>"/policy/library", "key"=>"UP-PAT"},
          "shadowed"=>false,
          "itemList"=>
           [{"resource"=>"/catalog/item",
             "key"=>"322209:2:1",
             "fields"=>
              {"bib"=>{"resource"=>"/catalog/bib", "key"=>"322209"},
               "call"=>{"resource"=>"/catalog/call", "key"=>"322209:2"},
               "barcode"=>"000013968861",
               "circulate"=>true,
               "copyNumber"=>1,
               "currentLocation"=>{"resource"=>"/policy/location", "key"=>"PATTEE-1A"},
               "homeLocation"=>{"resource"=>"/policy/location", "key"=>"PATTEE-1A"},
               "itemType"=>{"resource"=>"/policy/itemType", "key"=>"SCORE"},
               "library"=>{"resource"=>"/policy/library", "key"=>"UP-PAT"},
               "mediaDesk"=>nil,
               "shadowed"=>false}}]}}]}}
```

**Comment by ruthtillman** [comment]
Thanks @nicktiberi  - I think we'll be able to work with @mkutch after this sprint and maybe she can look into that then and see why it's not sending volumetric info!

**Comment by banukutlu** [comment]
Thanks for looking into this @nicktiberi and @ruthtillman, I am going to assign this to @mkutch and send it to backlog for now.

**Comment by ruthtillman** [comment]
@mkutch another record with same problem: https://catalog.libraries.psu.edu/catalog/2042050

Doug B reported that while placing each item individually on hold for patron (after their request) "in Workflows I kept getting the duplicate item already on hold error even though the call numbers and item IDs were different"

**Comment by mkutch** [comment]
This seems like a volumetric issue where these need to be in the |z field of callnumber. This is a larger cataloging issue that needs to be fixed.  For example,

https://catalog.libraries.psu.edu/catalog/2723696
https://catalog.libraries.psu.edu/catalog/2723560

have the same issue.

**Comment by ruthtillman** [comment]
I can bring this to cataloging -- is there any way to get a big report of these?

**Comment by ruthtillman** [comment]
I've handled the catkeys from this issue. Our fix is either to get a full report, which @mkutch may need to tease out or to fix on an ad-hoc basis.

**Comment by mkutch** [comment]
@ruthtillman  I'm thinking of doing these in small batches and it'll be a slightly kludgy extraction 😄

**Comment by mkutch** [comment]
@ruthtillman  I can work on getting a list, when I'm on your sprint.

**Comment by ruthtillman** [comment]
@mkutch great! In the meantime we'll just fix if they come up -- they rarely do
