### ISSUE TITLE
Notify patrons that they can opt into wage garnishment

### ISSUE THREAD

**Issue by nicktiberi** [psu-libraries/myaccount#490]
Now that faculty and staff patrons can opt into wage garnishment via MyAccount, it might be helpful to notify them in some way if they are eligible to opt into wage garnishment (currently represented by `eligible_for_wage_garnishment?` in the `Patron` model).

Possibilities for how to implement this include:
- showing a link to the "Accept Lending Policy" page on the summary page
- forwarding eligible users to the "Accept Lending Policy" page when they try to place a hold using the "I Want It" button in the catalog

**Comment by nicktiberi** [comment]
@ruthtillman - thoughts on this for UI to prompt eligible users to accept lending policy?

<img width="1194" alt="Screen Shot 2022-05-10 at 12 33 29 PM" src="https://user-images.githubusercontent.com/639920/167678479-c968aaf6-b59b-4c02-9b29-3d8baf1783bb.png">

**Comment by ruthtillman** [comment]
looks good to me -- I will check with the access services person, but I like it!

**Comment by ruthtillman** [comment]
Update -- Chris H says it looks good, so we can move forward!

**Comment by ruthtillman** [comment]
@nicktiberi since this isn't a thing that I can easily review live, should we schedule a time to just walk through it early next week and approve/deploy?

@banukutlu do you want to be part of that?

**Comment by nicktiberi** [comment]
> @nicktiberi since this isn't a thing that I can easily review live, should we schedule a time to just walk through it early next week and approve/deploy?
> 
> @banukutlu do you want to be part of that?

That sounds good to me. Should Maryam be part of that? She may need to bar one of us and set our garnish date to all 0s in production.

**Comment by banukutlu** [comment]
> @nicktiberi since this isn't a thing that I can easily review live, should we schedule a time to just walk through it early next week and approve/deploy?
> 
> @banukutlu do you want to be part of that?

sure that sounds good!

**Comment by ruthtillman** [comment]
@nicktiberi I'm ok doing a walkthrough with whichever non-prod you'd been using. When we deploy, however, we can test again and I'll see if she can bar one of us or maybe someone can talk @whereismyjetpack into unbarring his account for real. 😂
