### ISSUE TITLE
Put up notice for update on May 24th Symphony update

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/myaccount#494]
Morning of 5/23, put up notice:

```Scheduled maintenance: My Account will be unavailable on May 24, 2022 from approximately 6-6:45am Eastern```

(do we need to put it into maintenance mode?)

**Comment by banukutlu** [comment]
@ruthtillman I will be OOO starting from 5/23, @whereismyjetpack nicely agreed to do this, thanks!

**Comment by ruthtillman** [comment]
Thanks so much @whereismyjetpack! 👍 🍵

**Comment by banukutlu** [comment]
@ruthtillman We probably won't need the maintenance mode, afair that has been the case so far, but if I am mistaken and if it needs to be put in the maintenance mode, below are the settings to edit:

```
maintenance_mode: false
# Maintenance until text for date/time
maintenance_until:
```
