### ISSUE TITLE
Holds

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/myaccount#5]
Holds page: View and Manage Holds

* [x] View list
* ~[ ] Cancel hold~ (see #8) 
* ~[ ] Change hold pickup location and/or date no longer needed~ (see #62)

Documented: https://github.com/psu-libraries/psulib_blacklight/wiki/My-Account-Components#holds-management

**Comment by cdmo** [comment]
Seems like we don't use the `placedLibrary` field at all in the display. Can someone confirm that? I can see on our 910007356 test account that the item this item:

![Screenshot 2019-12-18 10 32 01](https://user-images.githubusercontent.com/523381/71099648-a3279700-2181-11ea-9f8d-c5ddfd858076.png)

Has a `placedLibrary` (`ABINGTON`) field, but it is not being displayed. Instead we are displaying `pickupLibrary` it would appear.

**Comment by cdmo** [comment]
A separate thing: why do we have a column for "availability" _and_  "pickup at"?
![Screenshot 2019-12-18 10 51 12](https://user-images.githubusercontent.com/523381/71101250-5c876c00-2184-11ea-8610-ff24eee6c7bd.png)

In the test accounts that have holds, these values are the same in the "Ready for Pickup" table.

I'd propose we get rid of the "Availability" column in the "Ready for Pickup" table unless anyone sees a reason we shouldn't.

**Comment by cdmo** [comment]
I'd recommend "Not ready for pickup" or something like that. "Outstanding Holds" is ambiguous. If you haven't picked up your hold, wouldn't that be "outstanding" from the perspective of a patron?

![Screenshot 2019-12-18 11 47 43](https://user-images.githubusercontent.com/523381/71105837-35349d00-218c-11ea-87f1-237b41f739be.png)

**Comment by cdmo** [comment]
Another thing. This outstanding holds table is, in general, really confusing to me. A suggested simplification could be:
Title and Status

If it were me as a patron, I'd probably want to know when I placed the hold and what the status is and when the library is going to give up.

I'll code it up as it is, just saying, it's kinda weird to me.

![Screenshot 2019-12-18 12 06 24](https://user-images.githubusercontent.com/523381/71107293-d15fa380-218e-11ea-84fa-8c09d3332f2e.png)

**Comment by cdmo** [comment]
@mkutch A specific question for you. Is "Status" in the "Outstanding Holds" table just always "Active"? The `status` field is (from the sample data I've seen) always `PLACED`. I'm assuming there's logic to just make that only show "Active". Is that right? Or is the value mapped from somewhere in the response data from the web service.

![Screenshot 2019-12-18 15 45 04](https://user-images.githubusercontent.com/523381/71121898-61144a80-21ad-11ea-91cc-c7e48d51bee0.png)

**Comment by mkutch** [comment]
@cdmo You can also have `status: "SUSPENDED"` . Talked with Chris about this and he said an instructor can book/reserve an item for their class ahead of time. The instructor cannot do this on their own and has to go to access services. Access services sets the `suspendBeginDate` and `suspendEndDate`. 

![image](https://user-images.githubusercontent.com/43478453/71186035-830fda80-224a-11ea-8228-96302978794d.png)

**Comment by cdmo** [comment]
Thanks! @mkutch does one of our test accounts have this record?

**Comment by mkutch** [comment]
@cdmo first test account has this record.

**Comment by mkutch** [comment]
Re  I'd think the patron would want/need to know where they are in the hold queue especially if there are a lot of holds on the item.  Also the need for pickup library, because they can change that option.

**Comment by cdmo** [comment]
Still think the language could be improved. I.e, "Your position in the holds queue" is very librarian-speak, would rather plain English.

**Comment by cdmo** [comment]
Hey @mkutch on this record the status is `SUSPENDED`, but we display "Inactive"
![Screenshot 2019-12-19 14 32 25](https://user-images.githubusercontent.com/523381/71203655-67b5c700-226c-11ea-8be7-73d561551ad2.png)

Is this because `suspendEndDate` is not set?  Not sure what else could trigger that status display.

**Comment by mkutch** [comment]
@cdmo Chris and I were testing the logic which displays the logic for the display of Inactive status. As you noticed the suspendEndDate is not set. Chris said this would never happen because they set the suspend begin and end dates. So you can ignore this case. We forgot to remove this, sorry for the confusion.

**Comment by cdmo** [comment]
I added a condition that checks for this and displays Inactive already, so it's in there. No biggie.

**Comment by mkutch** [comment]
@cdmo Correct, we don't use the `placedLibrary` field in the display.

**Comment by ruthtillman** [comment]
Looking through all this, let's discuss briefly at our next meeting and then I'll document. I do think that in one's outstanding holds (definitely ok with renaming) it's potentially important to show where one is in the holds queue. Because of recalls, etc., this isn't quite like public libraries... (though commonwealth borrowers don't recall, so a popular book that several of them have on hold could easily have 4 or 5 holds on it) but seeing you're in position 1 or position 4 can make a difference between whether you cancel and buy it or keep waiting or ?

**Comment by cdmo** [comment]
One other observation about interaction in holds that's kinda gnawing at me:

On the holds page there are two groups of holds. A current behavior in elibrary is that when you check a box from the "holds ready" group *and* the "outstanding holds" group and then click the Cancel Holds button at the bottom of the page, only the checked holds from the Outstanding Holds group will be processed. Also, when you check boxes from both groups and hit the cancel button that's just below the ready holds group only the checked holds from the holds ready group will be deleted. 

This is probably fine, just kinda weird and thought I'd bring it up.

![Screenshot_2020-01-30 My Account](https://user-images.githubusercontent.com/523381/73452182-5b2a9100-4337-11ea-80dc-89576feb32ea.png)

**Comment by ruthtillman** [comment]
🤔 There's definitely a good logic for separating "these are the ones available and you can do X to them" and "these are the ones not available and you can do X, Y, and Z to them." But I also find it a weird/frustrating usability experience. 😒 Open to ideas about other ways of displaying them, but I think the functionality is kind of limited by the different ways you can interact with the two groups.

**Comment by cdmo** [comment]
Another thing I discovered today: if you try to modify the pick up by date for a hold not yet ready whose current pickup by date has passed, Sirsi responds with an error like "the pickup date has passed, you can't change it." Our app as it is now just returns an error saying it couldn't do it.

I _think_ it's okay that we don't display the specific error message here because this scenario is so unlikely, but I wanted to check with you on whether or not we should modify our app to pass this particular error message along to the user, instead of the generic one in place.

**Comment by ruthtillman** [comment]
I think saying it can't do it and to contact your campus library might be the best bet? The people on the desk can make different kinds of edits.

**Comment by ruthtillman** [comment]
The current implementation looks good.
