### ISSUE TITLE
No-Recalls: Create Illiad user

### ISSUE THREAD

**Issue by whereismyjetpack** [psu-libraries/myaccount#565]
When placing a loan on behalf of a user, if the user does not exist in illiad we need to create the user. 

In looking at this we might need to get more information out of symphony for the user. 

We'll need to match up symphony library with illiad "site" I think 

Below are the following fields with what I think they should be matched up with 

| Illiad                   | Patron                                                                  |
| ----------------| ---------------------------------------------- |
| UserName          | patron.id                                                              |
| ExternalUserId   | patron.id                                                              |
| LastName          | patron.last_name                                                 |
| FirstName          | patron.first_name                                                |
| EmailAddress    | presently not available, address1 in symphony   |
| Site                    | patron.library                                                        | 

(RKT:) Other default fields/values for creation:

| Field | Value |
| --- | --- |
| DeliveryMethod | "Hold for Pickup" |
| LoanDeliveryMethod | "Hold for Pickup" |
| NotificationMethod | "Electronic" |

```
  "UserName": "", 
  "ExternalUserId": "",
  "LastName": "",
  "FirstName": "",
  "EmailAddress": " 
  "Phone": null,
  "Department": "Libraries",
  "NVTGC": "UPILL",
  "NotificationMethod": "Electronic",
  "DeliveryMethod": "Hold for Pickup",
  "LoanDeliveryMethod": "Hold for Pickup",
  "LastChangedDate": null,
  "AuthorizedUsers": null,
  "Cleared": "Yes",
  "Web": true,
  "Address": null,
  "Address2": null,
  "City": null,
  "State": null,
  "Zip": null,
  "Site": "Pattee Commons Services Desk",
  "ExpirationDate": "2024-11-22T00:00:00",
  "Number": null,
  "UserRequestLimit": null,
  "Organization": "University Park",
  "Fax": null,
  "ShippingAcctNo": null,
  "ArticleBillingCategory": null,
  "LoanBillingCategory": null,
  "Country": null,
  "SAddress": null,
  "SAddress2": null,
  "SCity": null,
  "SState": null,
  "SZip": "article",
  "SCountry": null,
  "RSSID": "",
  "AuthType": "Default",
  "UserInfo1": null,
  "UserInfo2": null,
  "UserInfo3": null,
  "UserInfo4": null,
  "UserInfo5": null,
  "MobilePhone": null
}
```

Site to Library Mapping:

| Library                   | Site                                         |
| ----------------| ------------------------------- |
| UP-PAT             | Pattee Commons Services Desk |

**Comment by ruthtillman** [comment]
We'll use their default Symphony library for Site - when the account is created they'll get an email letting them the know that they can change settings in ILLiad itself. I added the other default fields we'll use when creating the account.

Current status: Put in the other default values I got from talking with Shane and Meg. Asked Shane if he could export me a list of library names so we can create the table without having to manually retype the locations. Text is not a 1:1 to our other hold maps.

**Comment by ruthtillman** [comment]
Got the rest of the mapping from OCR. Checking on the DSL-UP thing with Shane because it wasn't in the list at all, but he said UP will generally go to Pattee and then can be updated, so making sure there isn't anything I'm missing. However, @whereismyjetpack this should be at least 99% right:

```
ABINGTON: Abington
ALTOONA: Altoona
BEAVER: Beaver
BEHREND: Behrend
BERKS: Berks
BRANDYWINE: Brandywine
DUBOIS: DuBois
DSL-UP: Pattee Commons Services Desk
FAYETTE: Fayette
GALLEGHENY: Greater Allegheny
GREATVLY: Great Valley
HARRISBURG: Harrisburg
HAZLETON: Hazleton
LEHIGHVLY: Lehigh Valley
MONTALTO: Mont Alto
NEWKEN: New Kensington
SCHUYLKILL: Schuylkill
WSCRANTON: Scranton
SHENANGO: Shenango
WILKESBAR: Wilkes-Barre
WORLD: World
YORK: York
DSL-CARL: Dickinson Law - Carlisle
UP-ARCHIT: Pattee Commons Services Desk
UP-ARTSHUM: Pattee Commons Services Desk
UP-BUSINES: Pattee Commons Services Desk
UP-EDUBEHV: Pattee Commons Services Desk
UP-EMS: Pattee Commons Services Desk
UP-ENGIN: Pattee Commons Services Desk
UP-LIFESCI: Pattee Commons Services Desk
UP-MAPS: Pattee Commons Services Desk
UP-MEDICAL: Pattee Commons Services Desk
UP-MICRO: Pattee Commons Services Desk
UP-OFFICE: Pattee Commons Services Desk
UP-PAMS: Pattee Commons Services Desk
UP-PAT: Pattee Commons Services Desk
UP-SOCSCI: Pattee Commons Services Desk
UP-SPECCOL: Pattee Commons Services Desk
```
