### ISSUE TITLE
Symphony upgrade testing

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/myaccount#599]
Swap in the Symphony QA server's WebServices (if we're not using it already) and make sure everything is working as expected with the upgrade.

**Comment by whereismyjetpack** [comment]
This has been done

**Comment by whereismyjetpack** [comment]
this should be done, again

**Comment by ruthtillman** [comment]
I've testing hold placement, updating, cancellation, cancellation of a hold that was already at Pattee for me (serendipity, the copy of the database that was synched to Symphony QA had one), and then tested an ILL hold just to be sure that the data we're getting for that is all still also ok. Everything worked as expected. I renewed 2 items successfully and then successfully failed to renew one item (as expected, it cannot be renewed).

Looks good to go.
