### ISSUE TITLE
Checkouts/Renewals

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/myaccount#6]
Page: Checkouts/Renewals

* [x] View list of items checked out
* [x] Renew individual (check box)
* [x] Renew all - #74 
* [x] Custom error messages - #69 

Info on what we currently have displayed here: https://github.com/psu-libraries/psulib_blacklight/wiki/My-Account-Components#checkoutsrenewals

**Comment by banukutlu** [comment]
@ruthtillman @mkutch What are the possible statuses for the checkouts table other than `Overdue`? 

![Screen Shot 2019-12-09 at 11 58 37 AM](https://user-images.githubusercontent.com/6477867/70456059-6837ac00-1a7b-11ea-91b3-7a9e31a06e11.png)

@mkutch How are the statuses determined currently? There is Active/Inactive status field but also Overdue field?

**Comment by ruthtillman** [comment]
Only other one I can think of is Recalled. but maybe there's a list which has values? @mkutch ?

**Comment by mkutch** [comment]
talked with Chris and the other status besides "Overdue" that was recently implemented is "Claims returned" ... There should be one on that account, but isn't being displayed in my library account (separate issue I need to look into that)

**Comment by banukutlu** [comment]
@mkutch another question re `You owe` column on the checkouts page. Could you pls find a test account that has accrued? And could you pls confirm if I use the `estimateOverdueAmount ` field for this column with no other calculation?

**Comment by mkutch** [comment]
Yes that is the estimateOverdueAmount. I put an example in box for you.

**Comment by mkutch** [comment]
The logic regarding Status of items.  If `overdue` is `true` then check if `claimsReturnedDate` is NOT null then the status is `Claims returned` else status is `Overdue`.

**Comment by ruthtillman** [comment]
So are recalls just changed due dates or is there anything special about them?

**Comment by mkutch** [comment]
Recalled item will have a new due date and looks like this

![image](https://user-images.githubusercontent.com/43478453/70534550-4d237580-1b29-11ea-9e41-90465e0f824c.png)

Or if Overdue AND Recalled like this

![image](https://user-images.githubusercontent.com/43478453/70534590-60cedc00-1b29-11ea-9613-789216249d68.png)

**Comment by ruthtillman** [comment]
Thank you @mkutch ! And is there something in the due date response that'll have the recalled stuff clearly?

**Comment by mkutch** [comment]
Check if `recallDueDate` is NOT null.

**Comment by banukutlu** [comment]
@mkutch I realized that there are `circRecordList{status} = INACTIVE` checkout in the webservices response. I do not see those listed in the current myaccount checkouts page. So, should we filter INACTIVE ones out?

**Comment by cdmo** [comment]
I see that conversation about this already, but to me it is confusing to show two dates in the "Due Date" column when there is a recall. Why not just show the new recall due date? Or, alternatively, put labels next to each due date? Or make it a sentence, like "Was due at OLD_DUE_DATE and is now due at NEW_DUE_DATE because this item was recalled" Or something.

![Screenshot 2019-12-17 09 30 44](https://user-images.githubusercontent.com/523381/71004882-9e46e280-20b0-11ea-9317-0714272b1557.png)

**Comment by cdmo** [comment]
You could also do a "This item was recalled on RECALL_DATE and is now due on NEW_DUE_DATE". Anyway, just some ideas. This is not a big deal, just something we can easily/quickly clear up. Tagging @ruthtillman (forgot to in last comment)

**Comment by mkutch** [comment]
@banukutlu yes you want to display the `circRecordList{status} = ACTIVE` records in the Checkouts list.

**Comment by mkutch** [comment]
We could just not display the original due date and just have it display  Recalled and the recalled due date underneath it. @ruthtillman

**Comment by cdmo** [comment]
@mkutch yes, that's another good option. As it is now, to me, feels broken/buggy.

**Comment by mkutch** [comment]
@cdmo yes ...The original due date doesn't really serve a purpose once it's been recalled with a new due date.

**Comment by banukutlu** [comment]
@mkutch what are the rules for deciding on items that are eligible for renewal in the current system? 

<img width="630" alt="Screen Shot 2019-12-18 at 10 09 00 AM" src="https://user-images.githubusercontent.com/6477867/71097762-8b9adf00-217e-11ea-8714-618cf929bdaf.png">
 

fyi @ruthtillman

**Comment by mkutch** [comment]
@banukutlu It's redundant and doesn't really serve a purpose since it is a repeat of the total checkouts above.  Any checkout that is `Active` is eligible for renewal but it doesn't necessarily mean it will/can be renewed. Recalled and claims returned items are considered `Active` checkouts.

**Comment by banukutlu** [comment]
> @banukutlu It's redundant and doesn't serve a purpose since it is a repeat of the total checkouts above. Any checkout that is `Active` is eligible for renewal but it doesn't necessarily mean it will/can be renewed. Recalled and claims returned items are considered `Active` checkouts.
> 
> re `seenRenewalsRemaining` and `unseenRenewalsRemaining` counts you don't have to care if you are letting symphony deal with the renewals and determining if can or can't be renewed (due to reaching the limit). The `renewalCount` would be something you'd want to display.

thanks @mkutch for the explanation! This is helpful. OK, then it makes sense to just not show that eligible msg (confirming with @ruthtillman).

**Comment by mkutch** [comment]
@banukutlu There needs to be a checkbox for every item checked out... Every item can be renewed unless it has a bill or there is a hold on it or at the limit of it's reserve circ rule (talked briefly with Chris). I will put patron for you to test on box.

**Comment by mkutch** [comment]
Also from Chris regarding renew on a single account "There shouldn't be a limit, but, we discovered after we increased the charge limit to 500 for faculty/staff/grad students that there's some line of code somewhere in the bowels of SD that limits renewals to 200 items if renewing with My Library Account. We'd prefer that there wasn't, but SD wasn't able to change it"

**Comment by mkutch** [comment]
@banukutlu Here are the message number, sirsi message  and custom message

`messageList{code}=141`
Sirsi : `Override required to exceed renewal limit.`
Custom : `Denied -- Renewal limit reached, cannot be renewed.<br>Due date remains unchanged.`

7703
`messageList{code}=7703`
Sirsi : `Override required to exceed unseen renewal limit.`
Custom :  `Denied -- Renewal limit reached, cannot be renewed.<br>Due date remains unchanged.`

105
`messageList{code}=105`
Sirsi : `Item has been recalled`
Custom : `Denied -- Item has been recalled, cannot be renewed.<br>Due date remains unchanged.`

252
`messageList{code}=252`
Sirsi : Item has holds
Custom : ` Denied -- Item has holds, cannot be renewed.<br>Due date remains unchanged.`

46
`messageList{code}=46`
Sirsi : `Item on reserve, may not be renewed`
Custom : `Denied -- Item on reserve, cannot be renewed.<br>Due date remains unchanged.`

**Comment by mkutch** [comment]
@banukutlu Re java errors we can have this message
 `Unable to renew item, please contact your local PSU library.`  with a link/hyperlink https://libraries.psu.edu/about/libraries

**Comment by ruthtillman** [comment]
This is a very complex issue but looks good according to my reviews.
