### ISSUE TITLE
Checking ILLiad User Status 

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/myaccount#617]
We're already handling two possible cases: if they already have an account and if they need one created.

However, there's an occasional third case that my arise where a person doesn't fall into resident/etc cases but is also not ILLiad eligible. All users will be cleared by folks in ILL and they will block those who shouldn't get an account (and send them a nice note/help them with Symphony hold).

On our application side, we need to be sure that we detect cases when a person:
1. has an account
2. that account is blocked or disavowed

and just route them to regular hold placement as well. We'll need to see what the API returns.

Data from Shane:

```
jsa5227 is currently blocked if you want to try it to see what happens.

tae5199 is disavowed
```

ILLiad made a list of statuses:

Allowed Values | Description
-- | --
Yes | The user is allowed to use the system.
No | The user has not yet been vetted by staff.
New | User is new to the system and has not completed  their user profile. On their first login they will be forced to  complete their user profile.
DIS | The user is disavowed and not authorized to log in.
B | The user is blocked.
BO | The user is blocked due to an overdue. Overdue blocks are removed when the user no longer has overdue materials checked out.
BX | The user is blocked by an external system.

**Comment by whereismyjetpack** [comment]
I may simplify this and if the user creation fails for whatever reason handle it as a symphony only hold.
