### ISSUE TITLE
Modify hold

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/myaccount#62]
Change hold pickup location and/or date no longer needed

Left over from #58

**Comment by cdmo** [comment]
Just wanted to record the findings from Thursday: despite the ability to dynamically query all possible pickup locations for a patron and item combination, the list of pickup locations is set statically and is universal for all items and patrons.

**Comment by cdmo** [comment]
@mkutch This is a note to remind you/us that we need the permissions changed on the production web services so that fillByDate can be edited by patrons.

**Comment by cdmo** [comment]
@ruthtillman I have a UX question for you. In the current My Account the user encounters "confirm prompts" when attempting to cancel a hold - like "Are you sure you want to cancel these holds?" kind of thing. Do we want that in My Library?

**Comment by ruthtillman** [comment]
I think as long as we don't have a "cancel all holds" button so they'd have to at least select individual or select All and confirm, it's ok (with caveat below). I would not say that for a public library, but we aren't the kind of place which stacks up holds on books. In public libraries, if there are 15 people in a queue and you're 4 and accidentally cancel and have to get back on the list, you won't see that book for _months_. Here, it's not as dire and we even have ILL.

BUT I think that does mean we need a solid response message with titles, etc. That way a user can go back to the catalog to place the hold again if they see they accidentally canceled one unintentionally. We should test with users.

**Comment by cdmo** [comment]
Ok, cool. Well, here's a quick preview of a first attempt at creating a batch processing form section for holds:

![Screenshot 2020-01-21 10 33 12](https://user-images.githubusercontent.com/523381/72994581-59a41a80-3dc5-11ea-935c-72f1e4b83410.png)

One other nice thing is that we'll have a date picker widget "for free" with My Library because we're using the browser's native date picker (current My Account has a calendar icon that would seem to indicate a calendar widget, but it doesn't seem to work).

**Comment by ruthtillman** [comment]
Yes, that's a very nice blue vs. red button and different sections to make it easier to edit than cancel. 👍

**Comment by cdmo** [comment]
Hi @ruthtillman - @banukutlu brought up the following question during review of modifying holds:

> I was able to change the not needed after date without editing/selecting a pickup at, this seems to be not allowed in the current elibrary system. I just wanted to confirm that it is OK to update the not needed after date like this, which seems so to me 🤔

Basically I made it so you can specify either a pick up location change and/or pick up by date change. Doesn't have to be both. Current system enforces both, but there is no systematic reason that has to be the case. Would you like to continue enforcing this? I just made the call on my own as part of the redoing the user experience a bit that I talked about during our last My Account checkin. Thanks.

**Comment by ruthtillman** [comment]
"Basically I made it so you can specify either a pick up location change and/or pick up by date change." -- yes, I think this is how it should be. You shouldn't need to do both.

**Comment by ruthtillman** [comment]
Made edits to both kinds. Works as expected!
