### ISSUE TITLE
Investigate: Feasibility of Exporting Current checkouts as RIS

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/myaccount#675]
Because we are about to get rid of checkout histories, public services is interested in mitigation strategies that help folks keep track of what they've read (but make it their choices).

Is it possible to repurpose the export all bookmarks as RIS code work we just finished to allow folks to export all current checkouts as an RIS file? (A bonus might be doing the same with emailing yourself a copy of it, but this isn't as high priority)

Whether it's adding within My Account or a button that sends the person's catkeys over to the Catalog to handle the function, it would be located in the Checkouts/Renewals page.

== 

Email format for Catalog records from Symphony:

```
catalog URL: bib => key (appended to URL)
Title: bib => fields => title
Author: bib => fields => author
Call #: call => fields> dispCallNumber
```

Email format for ILL, based on fields from ILLiad:

```
Title: LoanTitle
Author: LoanAuthor
Date: LoanDate
Identifier: ISSN (why god!)
```

**Comment by Smullz622** [comment]
I assume this should be for all checkouts (Symphony & ILL) correct?

**Comment by ruthtillman** [comment]
@Smullz622 really good point -- I think it may have to just be Symphony because we won't necessarily have ILL data

If ILL is easy enough to get from the API we could create the absolute stubbiest record with whatever fields we have. But we don't have them paired with a catkey or fuller record, so let's focus on Symphony.

**Comment by Smullz622** [comment]
Update: There might be a way to include ILL in the export using the ILLiad API. Going to wait to close this until we can do some exploration on that. 

Also going to look into adding an email export option. @ruthtillman we probably want to consider what the minimum as well as ideal fields would be for this. Based on what we're already pulling from ILLiad, we can definitely provide title/author, probably ISSN/DOI and call number. Past that might be dependent on what I can find out from the ILLiad API exploration.

**Comment by ruthtillman** [comment]
@Smullz622 - is there a good way you can query the ILLiad API for books and get some kind of big output of the fields? Then I could do an overall analysis. Everything will have a title. I don't know if we can be 100% sure they'll have an author, but probably?

**Comment by whereismyjetpack** [comment]
I think we store the catkeys in `ItemInfo2` it might be cleaner to pull out catkeys on existing illiad holds, and pass them to the bulk_ris exporter so we can continue to use symphony as the source of truth for ris information?

**Comment by ruthtillman** [comment]
@whereismyjetpack this is a good idea! It will work for many ILLiad items but some do not come from Catalog-based requests and may be books that we specifically don't own. So perhaps there should first be a test for catkeys, followed by API data if no catkeys exist.

**Comment by ruthtillman** [comment]
Tested RIS import with file where I removed a couple fields and it worked just fine so if we're missing date or author we should be ok!
