### ISSUE TITLE
Custom error messages for renewals

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/myaccount#69]
Map these error codes to the custom messages for renewals:

`messageList{code}=141`
Sirsi : `Override required to exceed renewal limit.`
Custom : `Denied -- Renewal limit reached, cannot be renewed.<br>Due date remains unchanged.`

`messageList{code}=7703`
Sirsi : `Override required to exceed unseen renewal limit.`
Custom :  `Denied -- Renewal limit reached, cannot be renewed.<br>Due date remains unchanged.`

`messageList{code}=105`
Sirsi : `Item has been recalled`
Custom : `Denied -- Item has been recalled, cannot be renewed.<br>Due date remains unchanged.`

`messageList{code}=252`
Sirsi : Item has holds
Custom : ` Denied -- Item has holds, cannot be renewed.<br>Due date remains unchanged.`

`messageList{code}=46`
Sirsi : `Item on reserve, may not be renewed`
Custom : `Denied -- Item on reserve, cannot be renewed.<br>Due date remains unchanged.`

For java errors, add the generic error msg and with a link to https://libraries.psu.edu/about/libraries

**Comment by ruthtillman** [comment]
In revising overall error message:

- display shortened success/error messages if more than 25 items being renewed
- in both messages for error_html, change "Try again or contact us for help" to "Review list of checked out items below and contact us if you require assistance." link "contact us" to Ask a Librarian.

**Comment by ruthtillman** [comment]
👍
