### ISSUE TITLE
Do not link to PALCI records

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/myaccount#70]
PALCI records are not in the public catalog. When displaying, do not link.

**Comment by cdmo** [comment]
@mkutch So, what is the canonical way to determine if an item is "of PALCI"? itemType or homeLocation?

**Comment by ruthtillman** [comment]
Looks good.

**Comment by cdmo** [comment]
I talked with @mkutch today, the itemType is canonical. She said that Shane Burris said that it is reliable 99.9% of the time, it is populated by a dynamic process. It is rare that this process fails and in those cases ILL will fix manually. (Just wanted to record this)
