### ISSUE TITLE
Moving to Symphony SaaS

### ISSUE THREAD

**Issue by Smullz622** [psu-libraries/myaccount#700]
We may have more on this moving forward, but for now, here is a list of things impacted by Symphony where we will want to test the success & error path:

Symphony holds: 
- [ ] place new
- [ ] view holds
- [ ] cancel holds
- [ ] change hold pickup date and/or library
- [ ] accept lending policy

Symphony checkouts:
- [ ] view
- [ ] renew
- [ ] fines
- [ ] symphony export checkouts email

Additional:
- [ ] ILL holds & checkouts (uses symphony client for patron & bib info)

**Comment by whereismyjetpack** [comment]
@Smullz622 we should be able to test this on QA myaccount

**Comment by ajkiessl** [comment]
This is ready to go live on May 22nd.
