### ISSUE TITLE
Feature spec for checkouts

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/myaccount#78]

**Comment by cdmo** [comment]
Do you think we need more for this one @banukutlu? Currently we have spec for successful and unsuccessful renew attempts

**Comment by banukutlu** [comment]
> Do you think we need more for this one @banukutlu? Currently we have spec for successful and unsuccessful renew attempts

@cdmo What other specs you think we should add here?

**Comment by cdmo** [comment]
I don't know that's why I'm asking you... ? You did make this issue right? Maybe we didn't have any back then?

**Comment by banukutlu** [comment]
> I don't know that's why I'm asking you... ? You did make this issue right? Maybe we didn't have any back then?

I cannot remember what I had in mind when adding this, maybe we did not have those specs before. I am inclined to close this issue unless you can think of any specs to add, I cannot right now :)
