### ISSUE TITLE
Ability to place holds

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/myaccount#96]
- [x] `Hold#create` - @banukutlu 
- [x]  Include symphony client request for placing holds - @banukutlu 
- [x] ~`Hold#new` form with pickup location and pickup up by date. Can use existing update hold not yet ready update form - need to turn into a partial and call from another view for new.~ see #106
- [x] Ability to handle redirect to where request came from (blackcat record show)
- [x] Explore concept of API end point for hold creation to be used by BlackCat

**Comment by banukutlu** [comment]
@mkutch when placing holds with ws, it requires `SD-Working-LibraryID` header to be passed in. Would this be same as the pickup library or something else?

**Comment by mkutch** [comment]
Talked with @banukutlu and the SD-Working-LibraryID is the patron's library.

**Comment by cdmo** [comment]
@ruthtillman I am recommending we remove the "Reset" button here, all it does is reset the form (with two total inputs) back to their default state.

![Screenshot 2020-02-03 09 13 06](https://user-images.githubusercontent.com/523381/73660065-79f59400-4665-11ea-99ca-28ae73ec27b6.png)

I think it's more confusing than useful. Is that alright? We can keep "Cancel" and have it just take a user back to the catalog record they were in (as it does now)

**Comment by ruthtillman** [comment]
I think cancel taking them back to the catalog record makes sense. Some forms are complex enough to require resetting, but this does not seem to be one of them.

**Comment by cdmo** [comment]
this got autoclosed mistakenly, reopening

**Comment by ruthtillman** [comment]
Tested and behaves well. One question -- if I go directly to something like http://myaccount-qa.herokuapp.com/holds/new?catkey=2890523 and hit Cancel, it doesn't seem to do anything.

**Comment by cdmo** [comment]
Yep, that is note coded up yet. Will be functional early next week I think.

**Comment by ruthtillman** [comment]
Getting 500 error during holds placement for JSON response but it's working.

**Comment by banukutlu** [comment]
> Getting 500 error during holds placement for JSON response but it's working.

Fix for this issue added to https://github.com/psu-libraries/myaccount/pull/157
