### ISSUE TITLE
Production connections for WS and upgrade

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/myaccount#98]
Including an upgrade to the Sirsi Web Service to 6.0

**Comment by banukutlu** [comment]
just to note here: currently `Sirsi Web Services Version 6.0.1.200502245`

**Comment by cdmo** [comment]
`x_sirs_clientID` from #214

**Comment by cdmo** [comment]
Assigning to @mkutch because I think this is on her plate to figure out what `x_sirs_clientID` needs to be for prod (looking at permissions?)

**Comment by cdmo** [comment]
I think our lingering questions for this are: should either `symws_app_id` or `x_sirs_clientID` be different for production? @mkutch do you know?

**Comment by mkutch** [comment]
@banukutlu @cdmo A new clientID has been created and I'm emailing it to you.
