### ISSUE TITLE
Do not link to records with these item types

### ISSUE THREAD

**Issue by mkutch** [psu-libraries/myaccount#99]
The following item types are not in the public catalog. When displaying do not link.

 `CARRELKEY, EBOOKREADR, EQUIP14DAY, EQUIP24FEE, EQUIP24HR, EQUIP3DAY, EQUIP4HR, EQUIP5DAY, EQUIP7DAY, ILL, LAPTOP`

**Comment by cdmo** [comment]
@ruthtillman you have reviewed this already right? e.g., `PALCI` records don't try to link to the catalog.

**Comment by ruthtillman** [comment]
Oh yes I think so?

**Comment by cdmo** [comment]
@mkutch can you provide any catkeys for the items you mentioned at https://github.com/psu-libraries/myaccount/issues/99#issue-557750416

**Comment by ruthtillman** [comment]
Not Catkey -- but @mkutch could we do someone with a bill for an overdue Laptop?

**Comment by ruthtillman** [comment]
Looks good!
